### ISSUE TITLE
Exploring Python 3 Conversion

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1181]
In one of my recent patch I had a dependency on python 2.7.7+: `hmac.compare_digest`
@miketaylr mentioned in an email maybe we could think about upgrading the server python version.

But then I thought would it be hard to switch to Python 3, the full project.

It's probably not complete yet but it is working. I have been able to list issues, upload an image, create bugs. I haven't tested everything yet. I will create a PR but not to merge, just to share here. 
- [x] convert the code to python 3 syntax
- [x] check module compatibility with python 3
- [x] check and fix unit tests
- [ ] check and fix functional tests
- [ ] check input/output operation for the code
- [ ] fix documentation for python 3
- [ ] check nginx compatibility ( @miketaylr )
- [ ] server upgrade for python 3
- [ ] test on staging

**Comment by miketaylr** [comment]
Welcome to the future.

![hqdefault](https://cloud.githubusercontent.com/assets/67283/18915535/f93be0a8-8556-11e6-8851-9848e3e0b87e.jpeg)

**Comment by miketaylr** [comment]
Do you know what best practices are around setting up (newer) Python versions in a virtualenv? We'll need to do that on the server and in our dev boxes as well.

**Comment by karlcow** [comment]
> I have seen the Future, and it doesn't work.

![zardoz-head](https://cloud.githubusercontent.com/assets/505230/18936244/c6342cd6-8620-11e6-993c-d383db18ac27.jpeg)

**Comment by karlcow** [comment]
python 3 and 2 are in a two separate universe, in terms of paths and libraries. So installing on a computer is pretty safe. So that's quite cool. 

That said. Python has a new [venv](https://docs.python.org/3/library/venv.html). 

You can still use virtualenv and specify the language version you would like to use, for example.

```bash
mkvirtualenv --python=/usr/local/bin/python3 webcompatcom
```

it depends on your `which python3` answer will be. For example on MacOSX, it might be `/Library/Frameworks/Python.framework/Versions/3.4/bin/python3`


For the way I did it on my environment here. I didn't yet modify to a specific virtual environment tied to python 3. But in the specific branch to switch, I did first:

```
pip3 install -r config/requirements.txt
```

I probably have made a mess of my modules. but it's ok, when I'm back on master I can still reinstall the requirements.txt

It's all in the project anyway:

```
~/code/webcompatcom/env/lib/python2.7/site-packages/
```

This installed the specific version of the modules we are using. 

then used a bit of 2to3 and manual changes (There's still clean up to do and a lot of testing).
Then to be sure to run the right version

```bash
python3 run.py
```

The result is that I'm still using python2 in my general config, but I'm just trying things for now.

```bash
→ workon webcompatcom
(webcompatcom)09:00:51 ~/code/webcompat.com
→ which python
/Users/karl/.virtualenvs/webcompatcom/bin/python
(webcompatcom)09:01:01 ~/code/webcompat.com
→ /Users/karl/.virtualenvs/webcompatcom/bin/python
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> ^D
(webcompatcom)09:01:45 ~/code/webcompat.com
→ git status
On branch py3
nothing to commit, working directory clean
→ ls -F /Users/karl/.virtualenvs/webcompatcom/lib/
python2.7/
```

**Comment by karlcow** [comment]
The fun is starting. I'll go through them one by one.


```
→ nosetests-3.4 
EE.EE.EEE............E.E.........E....
======================================================================
ERROR: API access to comments greater than 30 returns pagination in Link
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/karl/code/webcompat.com/tests/test_api_urls.py", line 83, in test_api_comments_link_header_auth
    'last', 'page'])
  File "/Users/karl/code/webcompat.com/tests/test_api_urls.py", line 82, in <genexpr>
    self.assertTrue = all(x in rv.data for x in ['Link', 'rel', 'next',
nose.proxy.TypeError: Type str doesn't support the buffer API
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): api.github.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /repos/webcompat/webcompat-tests/issues/398/comments?callback=foo HTTP/1.1" 200 None
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: API issue for a non existent number returns JSON 404.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/karl/code/webcompat.com/tests/test_api_urls.py", line 46, in test_api_issues_out_of_range
    json_body = json.loads(rv.data)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
nose.proxy.TypeError: the JSON object must be str, not 'bytes'
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): api.github.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /repos/webcompat/webcompat-tests/issues/1000000 HTTP/1.1" 404 None
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: API access to labels without auth returns JSON 200.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/karl/code/webcompat.com/tests/test_api_urls.py", line 70, in test_api_labels_without_auth
    json_body = json.loads(rv.data)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
nose.proxy.TypeError: the JSON object must be str, not 'bytes'
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): api.github.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /repos/webcompat/webcompat-tests/labels HTTP/1.1" 200 None
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: API with wrong parameter returns JSON 404.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/karl/code/webcompat.com/tests/test_api_urls.py", line 113, in test_api_search_wrong_parameter
    json_body = json.loads(rv.data)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

======================================================================
ERROR: API access to user activity without auth returns JSON 401.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/karl/code/webcompat.com/tests/test_api_urls.py", line 105, in test_api_user_activity_without_auth
    json_body = json.loads(rv.data)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

======================================================================
ERROR: API with wrong category returns JSON 404.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/karl/code/webcompat.com/tests/test_api_urls.py", line 62, in test_api_wrong_category
    json_body = json.loads(rv.data)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

======================================================================
ERROR: API with wrong route returns JSON 404.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/karl/code/webcompat.com/tests/test_api_urls.py", line 54, in test_api_wrong_route
    json_body = json.loads(rv.data)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

======================================================================
ERROR: testBase64ScreenshotUploads (tests.test_uploads.TestUploads)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/karl/code/webcompat.com/tests/test_uploads.py", line 143, in testBase64ScreenshotUploads
    rv = test_client.post('/upload/', data=dict())
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/werkzeug/test.py", line 788, in post
    return self.open(*args, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/testing.py", line 108, in open
    follow_redirects=follow_redirects)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/werkzeug/test.py", line 751, in open
    response = self.run_wsgi_app(environ, buffered=buffered)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/werkzeug/test.py", line 668, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/werkzeug/test.py", line 871, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/karl/code/webcompat.com/webcompat/api/uploads.py", line 123, in upload
    upload = Upload(imagedata)
  File "/Users/karl/code/webcompat.com/webcompat/api/uploads.py", line 42, in __init__
    self.image_object = self.to_image_object(imagedata)
  File "/Users/karl/code/webcompat.com/webcompat/api/uploads.py", line 56, in to_image_object
    return Image.open(BytesIO(base64.b64decode(imagedata)))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/base64.py", line 90, in b64decode
    return binascii.a2b_base64(s)
nose.proxy.Error: Incorrect padding
-------------------- >> begin captured logging << --------------------
PIL.PngImagePlugin: DEBUG: STREAM b'IHDR' 16 13
PIL.PngImagePlugin: DEBUG: STREAM b'IDAT' 41 10
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: testRegularUploads (tests.test_uploads.TestUploads)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/karl/code/webcompat.com/tests/test_uploads.py", line 115, in testRegularUploads
    rv = test_client.post('/upload/', data=dict())
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/werkzeug/test.py", line 788, in post
    return self.open(*args, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/testing.py", line 108, in open
    follow_redirects=follow_redirects)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/werkzeug/test.py", line 751, in open
    response = self.run_wsgi_app(environ, buffered=buffered)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/werkzeug/test.py", line 668, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/werkzeug/test.py", line 871, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/karl/code/webcompat.com/webcompat/api/uploads.py", line 114, in upload
    if 'image' in request.files and request.files['image'].filename:
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/karl/code/webcompat.com/tests/test_uploads.py", line 107, in files
    d['image'] = TestingFileStorage(stream=StringIO(f.read()),
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/codecs.py", line 313, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
nose.proxy.UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 4: invalid start byte
-------------------- >> begin captured logging << --------------------
PIL.Image: DEBUG: Importing BmpImagePlugin
PIL.Image: DEBUG: Importing BufrStubImagePlugin
PIL.Image: DEBUG: Importing CurImagePlugin
PIL.Image: DEBUG: Importing DcxImagePlugin
PIL.Image: DEBUG: Importing EpsImagePlugin
PIL.Image: DEBUG: Importing FitsStubImagePlugin
PIL.Image: DEBUG: Importing FliImagePlugin
PIL.Image: DEBUG: Importing FpxImagePlugin
PIL.Image: DEBUG: Importing GbrImagePlugin
PIL.Image: DEBUG: Importing GifImagePlugin
PIL.Image: DEBUG: Importing GribStubImagePlugin
PIL.Image: DEBUG: Importing Hdf5StubImagePlugin
PIL.Image: DEBUG: Importing IcnsImagePlugin
PIL.Image: DEBUG: Importing IcoImagePlugin
PIL.Image: DEBUG: Importing ImImagePlugin
PIL.Image: DEBUG: Importing ImtImagePlugin
PIL.Image: DEBUG: Importing IptcImagePlugin
PIL.Image: DEBUG: Importing JpegImagePlugin
PIL.Image: DEBUG: Importing Jpeg2KImagePlugin
PIL.Image: DEBUG: Importing McIdasImagePlugin
PIL.Image: DEBUG: Importing MicImagePlugin
PIL.Image: DEBUG: Importing MpegImagePlugin
PIL.Image: DEBUG: Importing MpoImagePlugin
PIL.Image: DEBUG: Importing MspImagePlugin
PIL.Image: DEBUG: Importing PalmImagePlugin
PIL.Image: DEBUG: Importing PcdImagePlugin
PIL.Image: DEBUG: Importing PcxImagePlugin
PIL.Image: DEBUG: Importing PdfImagePlugin
PIL.Image: DEBUG: Importing PixarImagePlugin
PIL.Image: DEBUG: Importing PngImagePlugin
PIL.Image: DEBUG: Importing PpmImagePlugin
PIL.Image: DEBUG: Importing PsdImagePlugin
PIL.Image: DEBUG: Importing SgiImagePlugin
PIL.Image: DEBUG: Importing SpiderImagePlugin
PIL.Image: DEBUG: Importing SunImagePlugin
PIL.Image: DEBUG: Importing TgaImagePlugin
PIL.Image: DEBUG: Importing TiffImagePlugin
PIL.Image: DEBUG: Importing WebPImagePlugin
PIL.Image: DEBUG: Importing WmfImagePlugin
PIL.Image: DEBUG: Importing XbmImagePlugin
PIL.Image: DEBUG: Importing XpmImagePlugin
PIL.Image: DEBUG: Importing XVThumbImagePlugin
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Test that we are receiving the appropriate text file.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/karl/code/webcompat.com/tests/test_urls.py", line 103, in test_rate_limit
    rv = self.app.get('/rate_limit')
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/werkzeug/test.py", line 778, in get
    return self.open(*args, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/testing.py", line 108, in open
    follow_redirects=follow_redirects)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/werkzeug/test.py", line 751, in open
    response = self.run_wsgi_app(environ, buffered=buffered)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/werkzeug/test.py", line 668, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/werkzeug/test.py", line 871, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/karl/code/webcompat.com/webcompat/views.py", line 248, in show_rate_limit
    rl = json.loads(body)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
nose.proxy.TypeError: the JSON object must be str, not 'bytes'
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): api.github.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /rate_limit HTTP/1.1" 200 None
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 38 tests in 4.946s

FAILED (errors=10)
```

**Comment by karlcow** [comment]
from 10 errors to 1. Progress.

```
→ nosetests-3.4 
.......................E..............
======================================================================
ERROR: testRegularUploads (tests.test_uploads.TestUploads)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/karl/code/webcompat.com/tests/test_uploads.py", line 115, in testRegularUploads
    rv = test_client.post('/upload/', data=dict())
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/werkzeug/test.py", line 788, in post
    return self.open(*args, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/testing.py", line 108, in open
    follow_redirects=follow_redirects)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/werkzeug/test.py", line 751, in open
    response = self.run_wsgi_app(environ, buffered=buffered)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/werkzeug/test.py", line 668, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/werkzeug/test.py", line 871, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/karl/code/webcompat.com/webcompat/api/uploads.py", line 117, in upload
    if 'image' in request.files and request.files['image'].filename:
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/karl/code/webcompat.com/tests/test_uploads.py", line 107, in files
    d['image'] = TestingFileStorage(stream=StringIO(f.read()),
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/codecs.py", line 313, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa2 in position 4: invalid start byte

----------------------------------------------------------------------
Ran 38 tests in 5.971s

FAILED (errors=1)
```

**Comment by karlcow** [comment]
yoohoo. 👹 

```
→ nosetests-3.4
......................................
----------------------------------------------------------------------
Ran 38 tests in 7.311s

OK
```

Unit tests done! (or mostly, because by fixing the issues we had I realized we are maybe not square enough for i/o operation. We might want to be stricter on many things.)

I should create a score card at the top.

**Comment by miketaylr** [comment]
http://serverfault.com/a/633633 for some hints on changing uwsgi to use a python3 interpreter when we get there.

**Comment by karlcow** [comment]
Closing in favor of #1332
