### ISSUE TITLE
npm start throws error b/c Flask(?)

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#1317]
run `npm start` on master

```
Traceback (most recent call last):
  File "run.py", line 43, in <module>
    raise ImportError('{0}\n\n{1}'.format(e, IMPORT_ERROR))
ImportError: cannot import name FlaskForm


==============================================
It seems like you don't have all dependencies.
Please re-run:
    pip install -r requirements.txt
==============================================
```

`pip install -r config/requirements.txt `

```
Requirement already satisfied: Babel==2.3.4 in /Library/Python/2.7/site-packages (from -r config/requirements.txt (line 1))
Requirement already satisfied: blinker==1.4 in /Library/Python/2.7/site-packages (from -r config/requirements.txt (line 2))
Requirement already satisfied: Flask==0.12 in /Library/Python/2.7/site-packages (from -r config/requirements.txt (line 3))
Requirement already satisfied: Flask-Limiter==0.9.3 in /Library/Python/2.7/site-packages (from -r config/requirements.txt (line 4))
Requirement already satisfied: Flask-SQLAlchemy==2.1 in /Library/Python/2.7/site-packages (from -r config/requirements.txt (line 5))
Requirement already satisfied: Flask-WTF==0.14.2 in /Library/Python/2.7/site-packages (from -r config/requirements.txt (line 6))
Requirement already satisfied: GitHub-Flask==3.1.5 in /Library/Python/2.7/site-packages (from -r config/requirements.txt (line 7))
Requirement already satisfied: nose==1.3.7 in /Library/Python/2.7/site-packages (from -r config/requirements.txt (line 8))
Requirement already satisfied: pep8==1.7.0 in /Library/Python/2.7/site-packages (from -r config/requirements.txt (line 9))
Requirement already satisfied: Pillow==4.0.0 in /Library/Python/2.7/site-packages (from -r config/requirements.txt (line 10))
Requirement already satisfied: requests==2.13.0 in /Library/Python/2.7/site-packages (from -r config/requirements.txt (line 11))
Requirement already satisfied: ua-parser==0.7.2 in /Library/Python/2.7/site-packages (from -r config/requirements.txt (line 12))
Requirement already satisfied: WTForms==2.1 in /Library/Python/2.7/site-packages (from -r config/requirements.txt (line 13))
Requirement already satisfied: pytz>=0a in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from Babel==2.3.4->-r config/requirements.txt (line 1))
Requirement already satisfied: itsdangerous>=0.21 in /Library/Python/2.7/site-packages (from Flask==0.12->-r config/requirements.txt (line 3))
Requirement already satisfied: Werkzeug>=0.7 in /Library/Python/2.7/site-packages (from Flask==0.12->-r config/requirements.txt (line 3))
Requirement already satisfied: Jinja2>=2.4 in /Library/Python/2.7/site-packages (from Flask==0.12->-r config/requirements.txt (line 3))
Requirement already satisfied: click>=2.0 in /Library/Python/2.7/site-packages (from Flask==0.12->-r config/requirements.txt (line 3))
Requirement already satisfied: six>=1.4.1 in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from Flask-Limiter==0.9.3->-r config/requirements.txt (line 4))
Requirement already satisfied: limits in /Library/Python/2.7/site-packages (from Flask-Limiter==0.9.3->-r config/requirements.txt (line 4))
Requirement already satisfied: SQLAlchemy>=0.7 in /Library/Python/2.7/site-packages (from Flask-SQLAlchemy==2.1->-r config/requirements.txt (line 5))
Requirement already satisfied: olefile in /Library/Python/2.7/site-packages (from Pillow==4.0.0->-r config/requirements.txt (line 10))
Requirement already satisfied: MarkupSafe>=0.23 in /Library/Python/2.7/site-packages (from Jinja2>=2.4->Flask==0.12->-r config/requirements.txt (line 3))
```
@karlcow maybe you could help?

Might be related to https://github.com/webcompat/webcompat.com/pull/1307 ?

(Site note...  `pip install -r requirements.txt` -> `pip install -r config/requirements.txt `)

**Comment by karlcow** [comment]
hmm you are not working in virtualenv for the development I see that all libraries are installed in your root. That's not recommended, because any other projects will create conflicts.

But that's not the bug.

what returns status and git log.

```
git status 
git log --oneline --since=1day
```

```
2ac4caf Merge pull request #1277 from webcompat/issues/982/1
904941e Issue #982. Fix tests that fail in Intern 3, that didn't in Intern 2.
b5db42c Issue #982. Use WindowHelpers blob methods in upload tests.
1256347 Issue #982. Add a LOCALHOST-only /test-files/ route, and a window-helpers.js.
fe9b6c2 Issue #982. Use FunctionalHelpers.visibleByQSA when wanting to wait for a loaded DOM element.
8d70512 Issue #982. Intern 3 wants paths to real files.
36749aa Issue #982. Update Travis configs to not need standalone selenium anymore.
8cadb0c Issue #982. Update docs on how to run Intern.
a3e242d Merge pull request #1315 from vladikoff/patch-3
07a91a1 fix npm init command
6de15bf Merge pull request #1313 from webcompat/issues/1312/1
eb4f525 Issue #1312. Add Secure flag to session cookie.
```

**Comment by karlcow** [comment]
for what is worth `npm run start` fails for me too.
but it's not how I start the server.

I start with `python run.py` 

```
→ npm run start

> webcompat@ start /Users/karl/code/webcompat.com
> source env/bin/activate && python run.py

('secrets', '/Users/karl/code/webcompat.com')
Traceback (most recent call last):
  File "run.py", line 43, in <module>
    raise ImportError('{0}\n\n{1}'.format(e, IMPORT_ERROR))
ImportError: No module named flask_wtf


==============================================
It seems like you don't have all dependencies.
Please re-run:
    pip install -r requirements.txt
==============================================


npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/karl/.nvm/versions/node/v4.0.0/bin/node" "/Users/karl/.nvm/versions/node/v4.0.0/bin/npm" "run" "start"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! webcompat@ start: `source env/bin/activate && python run.py`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webcompat@ start script 'source env/bin/activate && python run.py'.
npm ERR! This is most likely a problem with the webcompat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     source env/bin/activate && python run.py
npm ERR! You can get their info via:
npm ERR!     npm owner ls webcompat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/karl/code/webcompat.com/npm-debug.log
```

**Comment by zoepage** [comment]
@karlcow interesting. 
I had to run `source env/bin/activate` manually. Then it worked. Will investigate further.
Thanks for the pointer!

**Comment by karlcow** [comment]
@zoepage note that you should probably reinstall your modules after starting virtualenv and not before.

**Comment by zoepage** [comment]
@karlcow yes :)

**Comment by magsout** [comment]
@karlcow 

>for what is worth npm run start fails for me too.

oh ? it's okk for me, weird..

**Comment by zoepage** [comment]
@karlcow what were your steps?
@magsout did you manage to check out the last master?

**Comment by magsout** [comment]
@karlcow 

>but it's not how I start the server.


Hum, I see in npm script : 

```
"start": "source env/bin/activate && python run.py",
```

**Comment by magsout** [comment]
@zoepage 

>@magsout did you manage to check out the last master?

ah no, so the recipes failed because of master ?

**Comment by magsout** [comment]
need to read all the issue, beforce comment ...

**Comment by zoepage** [comment]
@magsout no worries :)
looks like, which is weird. have a few ideas about the why I need to check.

**Comment by miketaylr** [comment]
> I start with python run.py

Same, I don't use any of the npm commands due to habit. My workflow:

`workon webcompat` (activates virtualenv, via [virtualenvwrapper](https://virtualenvwrapper.readthedocs.io/en/latest/command_ref.html))
`python run.py`
...hack...
`deactivate` (when i need to work in other virtualenvs for other projects)

**Comment by zoepage** [comment]
Yeah, looks like the npm start script is the issue. Have an idea, but have to test it tonight.
