### ISSUE TITLE
SUITE ERROR: test failure

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1324]
Looks like an intermittent login failure. All of my mehs.

From https://travis-ci.org/webcompat/webcompat.com/builds/197804908#L1041.

```SUITE ERROR

NoSuchElement: [POST http://localhost:4444/wd/hub/session/6f134c94-a74f-42b0-9d49-2788a3da538c/element / {"using":"css selector","value":".wc-Navbar-avatar"}] Unable to locate element: .wc-Navbar-avatar

For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html

Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'

System info: host: 'testing-gce-1aac69e0-d81a-4f99-8c63-ec8339683305', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-51-generic', java.version: '1.8.0_111'

Driver info: org.openqa.selenium.firefox.FirefoxDriver

Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, firefoxOptions={args=[], profile=UEsDBBQACAgIAPesQkoAAAAAAAAAAAAAAAAHAAAAdXNlci5qc51WTW/bMAy971cMOW3AKqTretlOXdcBA4Z1aFDsKMgSbauRJU0fcfPvR/mjSRNHbndKbJMS+fj4yOjBUeugfLconGnxiXhWQvdf6oo0TLXMAQHNCgVi8eFtyZSH91/exJ2nYAFtrHEhudTAVKj7Z4JGG8ln/DWE1rg1qUOwxNbS19uz9Nky788U6CrU6Pjx8vK52xiwAybwR0AAHkB8l86HK4yFK0C34OJhuKbBvB4pr51pgHrupA3URU2DbJLLxXL6osAKTxAOfauvlfEwnc1oLUyrlWEC79KsSsDWpv1Tg14hWgmpaXeLQdng02W0MYKpGexhE4xRnoBzxnGjvVH7cB+n72WljUbUGmgKcKvu0edz8eC9RKtgkAsOfETcSgyUcsd8nfdVUq+JsaApPAZwmqlUzFczqExlvYt6+rIWCuHkBp8Z54DljBoz90gHysEFP4nEU6Wkt4ptQdycL1e/DDInlfbTtDG+Erf6j9RYX3++JBIvMvd3P9FjwQoTw+dCMb1eHHOuT4gypeiDRzBSnLKH/ji2RysRbrQlbS0DKOkDHvA3SneKCYkGaxnI0E0j6zC5xIUsAIphYbAB8lTzibfRkhq7xuLZtAXFUwdFl0q6OEg5VVt3rCHRYoGBaIS23N6jyat1JNrUSjfZ8IBHJ8MWmaIA/xEfnOSBGicrqak1SvJtnqoaWmw7MuSTqeazQPuTSXq5ikUju1b53b286sj4Mt2cPCab8VN3DoVJRUHLE+q160NMs+34e9yIpizRDs6YtZ4g+0xLiy0VULKowrScjLBzbwf+TEd7zIcs20Y6I/dRqYLbkl4ZO/uPc7bZo0dEbu5/XpELwnZFOk7vgW1YPyGyonpYirFH8jw6jtvBQzfEspf0NE3H5/PcQ5zFYL71SrDiSIIkOufLUxran0o1C/hIYQM6zAyIvdF4ixSbjadQhq87UXtRpTwwx+uBN3NjtyE9u4mIjc1WDVn+Ii4+I4xBhJwU04p6JEKH6nMxvfr0an02th/SKMQZyAfbE9Iy7Djzy83e5PTdXN9NTpSg2Gl1FrlErekg9nrH9KOu24F+6Ot+TTm5nQ0zi3ZqJRBGXdGk/zMkqQHHJa+Br7/1gvW1//L6cUaYEDJFzGYmweTS/L/LsjJVlV4OW1xW+/d6qcv4GrUR27WQKrFPy6oO6sS023Mdb/wfaaNjI5AG98KOiIu0Szo4wGi3yqTVE4mNC+TMLrPre1X6aPsVYLdl/ANQSwcIy87bUaYDAAC2DAAAUEsBAhQAFAAICAgA96xCSsvO21GmAwAAtgwAAAcAAAAAAAAAAAAAAAAAAAAAAHVzZXIuanNQSwUGAAAAAAEAAQA1AAAA2wMAAAAA}, appBuildId=20161208153507, version=50.1.0, platform=LINUX, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, build=10d8e0fcc7440a130d8c32b534039188bd00a8b9, processId=5082, browserVersion=50.1.0, platformVersion=4.4.0-51-generic, name=tests/intern, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, idle-timeout=60, takesElementScreenshot=true, platformName=linux}]

Session ID: 4dd04bc9-ba5f-458b-abcd-2f610dca549c

*** Element info: {Using=css selector, value=.wc-Navbar-avatar}

  at nextTickCallbackWith0Args  <node.js:436:9>

  at Command.<anonymous>  <tests/functional/lib/helpers.js:107:14>

  at nextTickCallbackWith0Args  <node.js:436:9>

  at process._tickCallback  <node.js:365:13>

  at Object.login  <tests/functional/lib/helpers.js:71:8>

  at Suite.registerSuite.setup  <tests/functional/search-auth.js:25:32>

127.0.0.1 - - [02/Feb/2017 21:42:08] "GET /logout HTTP/1.1" 302 -

127.0.0.1 - - [02/Feb/2017 21:42:08] "GET / HTTP/1.1" 200 -

Expected fixture file: /home/travis/build/webcompat/webcompat.com/tests/fixtures/api/issues/labels.6665c4820456e6a813dcbbdddd690ffc.json

127.0.0.1 - - [02/Feb/2017 21:42:08] "GET /api/issues/labels?per_page=100 HTTP/1.1" 200 -

Expected fixture file: /home/travis/build/webcompat/webcompat.com/tests/fixtures/api/issues/category/needstriage.json

127.0.0.1 - - [02/Feb/2017 21:42:08] "GET /api/issues/category/needstriage HTTP/1.1" 200 -

5/5 tests failed
```

**Comment by zoepage** [comment]
@miketaylr just had issues with updating intern. Basically chai and dojo couldn't be updated, b/c of symlink. Related?

```
npm WARN update-linked node_modules/intern/node_modules/chai needs updating to 3.5.0 from 1.9.1 but we can't, as it's a symlink
npm WARN update-linked node_modules/intern/node_modules/dojo needs updating to 2.0.0-alpha.7 from 2.0.0-dev but we can't, as it's a symlink
```

**Comment by miketaylr** [comment]
Hmmmmm, it's possible. I didn't even bother to update, I just rm -rf and re-installed.

In the Travis environment, Intern is fresh-installed (or loaded from a previous cache) rather than updated.

**Comment by miketaylr** [comment]
We haven't seen this in a while, let's close.
