### ISSUE TITLE
HTTP POST on issues/new creates a 500

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1357]
a simple

   http POST http://localhost:5000/issues/new

explodes the code ;) 💣 

That could be handled in a better way:

```
127.0.0.1 - - [23/Feb/2017 10:15:50] "POST /issues/new HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/karl/code/webcompat.com/webcompat/views.py", line 174, in create_issue
    if spam in form.get('url'):
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by karlcow** [comment]
if we do an HTTP POST with empty parameters, we get 
https://github.com/webcompat/webcompat.com/blob/bb90834d0b8d60ac51d1ca7f636dcc8e3e543def/webcompat/views.py#L169

```python
form = request.form.copy()
```
In this case, 
```
request.form -> ImmutableMultiDict([])
form -> MultiDict([])
```
[ImmutableMultiDict](http://werkzeug.pocoo.org/docs/0.11/datastructures/#werkzeug.datastructures.ImmutableMultiDict) and [MultiDict](http://werkzeug.pocoo.org/docs/0.11/datastructures/#werkzeug.datastructures.MultiDict)

```python
>>> from werkzeug.datastructures import MultiDict
>>> d = MultiDict()
>>> d
MultiDict([])
>>> 'foo' in d.get('url')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: argument of type 'NoneType' is not iterable
>>> 'foo' in d.get('url', 'blah')
False
>>> d.get('url', 'blah')
'blah'
>>> d
MultiDict([])
>>> if not d:
...     print 'Out'
... else:
...     print 'Process it'
... 
Out
```

We are using form['ua_header'], form['reported_with'], form.get('url'), form.get('submit-type'), form['url'] with different syntaxes. All of these have a potential to fail if one of the parameters is empty. We should cater for those.

At least we could first handle the empty form case:

```python
    # copy the form so we can add the full UA string to it.
    form = request.form.copy()
```

to replace with:

```python
if request.form:
    form = request.form.copy()
else:
    # https://tools.ietf.org/html/rfc7231#section-6.5.1
    abort(400) 
```

That would solve part of the issue. But we should probably make it more robust to all the potential or non existing keys.

I'll put that on my todo list.

**Comment by miketaylr** [comment]
> I'll put that on my todo list.

Thanks Karl!

**Comment by miketaylr** [comment]
@karlcow is willing to mentor/review patches here if someone wants to tackle this before he can.

**Comment by jeanhl** [comment]
@karlcow, I'm trying to recreate this issue. Using the site normally only gives me POST 302. If this still needs fixing, I can poke around while I wait until #1385 gets more direction (since @miketaylr is on vacay).
![screen shot 2017-03-04 at 12 24 39 pm](https://cloud.githubusercontent.com/assets/20343358/23786550/8ecf0456-0522-11e7-92e0-d8b85cd3d5f9.png)

**Comment by jeanhl** [comment]
POST 302 running on localhost
![screen shot 2017-03-09 at 11 45 40 pm](https://cloud.githubusercontent.com/assets/20343358/23786618/f302f7d4-0522-11e7-9047-c9fbd77c45be.png)

**Comment by nj4710** [comment]
`127.0.0.1 - - [11/Mar/2017 00:01:11] "POST /issues/new HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/neha/webcompat.com/env/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/neha/webcompat.com/env/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/neha/webcompat.com/env/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/neha/webcompat.com/env/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/neha/webcompat.com/env/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/neha/webcompat.com/env/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/neha/webcompat.com/env/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/neha/webcompat.com/env/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/neha/webcompat.com/webcompat/views.py", line 178, in create_issue
    if spam in form.get('url'):
TypeError: argument of type 'NoneType' is not iterable
`

@karlcow  I sent a POST request from firefox and got this output.

**Comment by nj4710** [comment]
@karlcow  After applying your suggestions, I got:
`127.0.0.1 - - [11/Mar/2017 00:50:40] "GET /api/issues/category/needstriage HTTP/1.1" 304 -
127.0.0.1 - - [11/Mar/2017 00:51:01] "GET /issues/new HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2017 00:51:14] "POST /issues/new HTTP/1.1" 400 -
127.0.0.1 - - [11/Mar/2017 00:51:19] "POST /csp-report HTTP/1.1" 204 -
`

**Comment by jeanhl** [comment]
@nj4710 How did you get a POST 500? I'm trying to figure out what I wasn't doing right.

**Comment by nj4710** [comment]
@jeanhl  from firefox developer tools I changed the request method to POST and that gave me that error.

**Comment by jeanhl** [comment]
@nj4710  It worked! I'm so happy to see a bug. Thanks!

**Comment by nj4710** [comment]
@jeanhl  your welcome:).  
@karlcow  could you suggest some cases for form[ua_headers] and others, so that we can reproduce the error locally and try to resolve it
