### ISSUE TITLE
Failing "Reporting (auth) - Report button shows name " test

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1371]
```
FAIL: firefox on any platform - Reporting (auth) - Report button shows name (359ms)

AssertionError: expected 'Report via GitHub' to include 'Report as'

  at Command.<anonymous>  <tests/functional/reporting-auth.js:33:18>

  at nextTickCallbackWith0Args  <node.js:489:9>

  at Test.registerSuite.Report button shows name [as test]  <tests/functional/reporting-auth.js:32:10>

  at nextTickCallbackWith0Args  <node.js:489:9>

  at process._tickCallback  <node.js:418:13>
```

This one seems to intermittently fail on Travis.

**Comment by miketaylr** [comment]
Right now it seems like this is a perma-failure.

**Comment by miketaylr** [comment]
https://github.com/webcompat/webcompat.com/pull/1387 fixes this.
