### ISSUE TITLE
Investigate 500 when trying to report an issue

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1542]
Originally reported at https://github.com/webcompat/web-bugs/issues/6315.

```
<!-- @browser: Firefox Mobile 54.0 -->
<!-- @ua_header: Mozilla/5.0 (Android 6.0.1; Mobile; rv:54.0) Gecko/54.0 Firefox/54.0 -->
<!-- @reported_with: mobile-reporter -->

**URL**: https://webcompat.com/issues/new
**Browser / Version**: Firefox Mobile 54.0
**Operating System**: Android 6.0.1
**Problem type**: Mobile site is not usable

**Steps to Reproduce**
1. Navigate to: https://webcompat.com/issues/new
2. Reporting errors on this URL result in internal error: 
https://webcompat.com/issues/new?url=http://thebulletin.org/fusion-reactors-not-what-they%E2%80%99re-cracked-be10699&src=mobile-reporter
```

I don't get a 500, but we should look at server logs to see if there isn't something else at play.

**Comment by karlcow** [comment]
I suspect this is nginx which is replying 500?
Testing with a local instance. 

```
UnicodeEncodeError

UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 52: ordinal not in range(128)

```

which is due to 

```
127.0.0.1 - - [01/May/2017 06:37:51] "POST /issues/new HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/karl/code/webcompat.com/webcompat/views.py", line 196, in create_issue
    log.info('{ip} {url}'.format(ip=request.remote_addr, url=form['url']))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 52: ordinal not in range(128)
```

ok

The issues comes from the URI.

```
http://thebulletin.org/fusion-reactors-not-what-they%E2%80%99re-cracked-be10699
```

which is once encoded.

```
http://thebulletin.org/fusion-reactors-not-what-they’re-cracked-be10699
```

The character causing trouble is: 
* `’` RIGHT SINGLE QUOTATION MARK. 
* UNICODE: `U+2019` 
* UTF-8: `E2 80 99`

The fix is easy. The surprise is that it didn't happen before.

```python
    log.setLevel(logging.INFO)
    log.info('{ip} {url}'.format(ip=request.remote_addr,
                                 url=form['url'].encode('utf-8')))
```

**Comment by karlcow** [comment]
Pull request done.

**Comment by miketaylr** [comment]
Awesome work Karl.
