### ISSUE TITLE
FAIL: firefox on any platform - Labels (auth) - Label widget opens (20724ms)

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1601]
```
FAIL: firefox on any platform - Labels (auth) - Label widget opens (20724ms)

NoSuchElement: [POST http://localhost:4444/wd/hub/session/ec248dd4-bcae-426e-907d-8b13d36ee60e/element / {"using":"css selector","value":".js-LabelEditor"}] Unable to locate element: .js-LabelEditor

For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html

Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'

System info: host: 'testing-gce-e42aa373-80ae-4242-b3f4-91a00c35b132', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-51-generic', java.version: '1.8.0_111'

Driver info: org.openqa.selenium.firefox.FirefoxDriver

Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, firefoxOptions={args=[], profile=UEsDBBQACAgIAESJ1EoAAAAAAAAAAAAAAAAHAAAAdXNlci5qc51WTW/bMAy971cMOW3AKqTretlOXdcBA4Z1aFDsKMgSbauRJU0fcfPvR/mjSRNHbndKbJMS+fj4yOjBUeugfLconGnxiXhWQvdf6oo0TLXMAQHNCgVi8eFtyZSH91/exJ2nYAFtrHEhudTAVKj7Z4JGG8ln/DWE1rg1qUOwxNbS19uz9Nky788U6CrU6Pjx8vK52xiwAybwR0AAHkB8l86HK4yFK0C34OJhuKbBvB4pr51pgHrupA3URU2DbJLLxXL6osAKTxAOfauvlfEwnc1oLUyrlWEC79KsSsDWpv1Tg14hWgmpaXeLQdng02W0MYKpGexhE4xRnoBzxnGjvVH7cB+n72WljUbUGmgKcKvu0edz8eC9RKtgkAsOfETcSgyUcsd8nfdVUq+JsaApPAZwmqlUzFczqExlvYt6+rIWCuHkBp8Z54DljBoz90gHysEFP4nEU6Wkt4ptQdycL1e/DDInlfbTtDG+Erf6j9RYX3++JBIvMvd3P9FjwQoTw+dCMb1eHHOuT4gypeiDRzBSnLKH/ji2RysRbrQlbS0DKOkDHvA3SneKCYkGaxnI0E0j6zC5xIUsAIphYbAB8lTzibfRkhq7xuLZtAXFUwdFl0q6OEg5VVt3rCHRYoGBaIS23N6jyat1JNrUSjfZ8IBHJ8MWmaIA/xEfnOSBGicrqak1SvJtnqoaWmw7MuSTqeazQPuTSXq5ikUju1b53b286sj4Mt2cPCab8VN3DoVJRUHLE+q160NMs+34e9yIpizRDs6YtZ4g+0xLiy0VULKowrScjLBzbwf+TEd7zIcs20Y6I/dRqYLbkl4ZO/uPc7bZo0dEbu5/XpELwnZFOk7vgW1YPyGyonpYirFH8jw6jtvBQzfEspf0NE3H5/PcQ5zFYL71SrDiSIIkOufLUxran0o1C/hIYQM6zAyIvdF4ixSbjadQhq87UXtRpTwwx+uBN3NjtyE9u4mIjc1WDVn+Ii4+I4xBhJwU04p6JEKH6nMxvfr0an02th/SKMQZyAfbE9Iy7Djzy83e5PTdXN9NTpSg2Gl1FrlErekg9nrH9KOu24F+6Ot+TTm5nQ0zi3ZqJRBGXdGk/zMkqQHHJa+Br7/1gvW1//L6cUaYEDJFzGYmweTS/L/LsjJVlV4OW1xW+/d6qcv4GrUR27WQKrFPy6oO6sS023Mdb/wfaaNjI5AG98KOiIu0Szo4wGi3yqTVE4mNC+TMLrPre1X6aPsVYLdl/ANQSwcIy87bUaYDAAC2DAAAUEsBAhQAFAAICAgARInUSsvO21GmAwAAtgwAAAcAAAAAAAAAAAAAAAAAAAAAAHVzZXIuanNQSwUGAAAAAAEAAQA1AAAA2wMAAAAA}, appBuildId=20161208153507, version=50.1.0, platform=LINUX, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, build=e8593a539e2d7112f63bd7369d86c9568145c0cc, processId=6754, browserVersion=50.1.0, platformVersion=4.4.0-51-generic, name=tests/intern, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, idle-timeout=60, takesElementScreenshot=true, platformName=linux}]

Session ID: 393ec8d9-7b19-4d4f-9b96-7e0a26e5fb90

*** Element info: {Using=css selector, value=.js-LabelEditor}

  at nextTickCallbackWith0Args  <node.js:489:9>

  at Test.Label widget opens [as test]  <tests/functional/labels-auth.js:41:14>

  at nextTickCallbackWith0Args  <node.js:489:9>
```

**Comment by miketaylr** [comment]
I dunno if this is related to #712 or not, but it's the only currently failing test on master. 

(Note, the real functionality isn't busted, I've just verified).

**Comment by miketaylr** [comment]
Hmmm... I just deployed master to staging.webcompat.com, and the icon legit doesn't open. Possibly caused by something else. Investigating...

(I haven't deployed the v5.2.0 to master yet, phew)

**Comment by miketaylr** [comment]
Actually, this is a regression caused by https://github.com/webcompat/webcompat.com/commit/56d94cb996c160f1c4d27212d5f925ea89223924#diff-62ac21a69385d253b980039737102f05R23.

We switched from `button` to `.wc-Button`, but the label editor button is missing that class. Oops. :)~

(this is why flaky tests are a bad thing, we assume new failures are just flaky...)

**Comment by magsout** [comment]
@miketaylr ooops 😅

**Comment by miketaylr** [comment]
@magsout no worries, easy fix :p
