### ISSUE TITLE
Exception in webhook helpers.py

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1811]
```
2017-09-08 06:57:17,810 tracking Exception thrown:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./webcompat/webhooks/__init__.py", line 48, in hooklistener
    response = new_opened_issue(payload)
  File "./webcompat/webhooks/helpers.py", line 138, in new_opened_issue
    browser_label = extract_browser_label(issue_body)
  File "./webcompat/webhooks/helpers.py", line 34, in extract_browser_label
    browser = browser.translate(None, '()')
TypeError: translate() takes exactly one argument (2 given)
```

**Comment by miketaylr** [comment]
Failed here, with this UA string:

https://github.com/webcompat/web-bugs/issues/9733

`Mozilla/5.0 (Android 7.1.2; Mobile; rv:57.0) Gecko/57.0 Firefox/57.0`

**Comment by miketaylr** [comment]
Regressed by https://github.com/webcompat/webcompat.com/issues/1567.
