### ISSUE TITLE
Unable to report issues with attachment on Staging

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [webcompat/webcompat.com#1830]
URL: www.staging.webcompat.com  
Browser / Version: Firefox 55.0.3, Chrome 61.0.3163.100. 
Operating System: Windows 10 Pro

**Steps to Reproduce:**
1. Navigate to www.staging.webcompat.com.
2. Tap “Report bug” button.
3. Type in all the required info and upload a screenshot.
4. Tap the “Report” button and observe behavior.

**Expected Behavior:**
Issue is reported.

**Actual Behavior:**
Issue is not reported, a loading spinner is displayed indefinitely on the attachment area.

**Note**
1. Not reproducible when reporting an issue with no attachment. 
2. If the issue is reported and trying to attach a screenshot, an error message is received ("There was an error trying to upload the image.").
3. Screenshot attached.
4. Error: `TypeError: this.animate is not a function[Learn More]  webcompat.min.js:9:19934
	m.fn[b] https://staging.webcompat.com/js/webcompat.min.js:9:19934
	r https://staging.webcompat.com/js/webcompat.min.js:10:21405
	dispatch https://staging.webcompat.com/js/webcompat.min.js:8:28412
	add/r.handle https://staging.webcompat.com/js/webcompat.min.js:8:25151`

 **Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv; 

![bugnotreported](https://user-images.githubusercontent.com/12184325/30916873-22f06e3a-a3a3-11e7-963f-c68d7474924c.gif)

**Comment by miketaylr** [comment]
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./webcompat/api/uploads.py", line 143, in upload
    upload.save()
  File "./webcompat/api/uploads.py", line 106, in save
    os.makedirs(dest_dir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/srv/uploads/staging.webcompat.com/uploads/2017/9'
```

**Comment by karlcow** [comment]
For now, `chown -R user_id:group_id /srv/uploads/staging.webcompat.com/uploads`
where user_id:group_id are the owner of the server process.

For the next upload.

[os.makedirs](https://docs.python.org/2/library/os.html#os.makedirs) is calling [os.mkdir](https://docs.python.org/2/library/os.html#os.mkdir). 

> Create a directory named path with numeric mode mode. The default mode is 0777 (octal). If the directory already exists, OSError is raised.

But that's not it.

```python
>>> import os
>>> os.makedirs('tmp/foo')
>>> os.makedirs('tmp/foo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/karl/.virtualenvs/shoki/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: 'tmp/foo'
```

The error is permission denied.

> On some systems, mode is ignored. Where it is used, the current umask value is first masked out. If bits other than the last 9 (i.e. the last 3 digits of the octal representation of the mode) are set, their meaning is platform-dependent. On some platforms, they are ignored and you should call chmod() explicitly to set them.

I wonder if it's the default umask value we have for nginx.

**Comment by miketaylr** [comment]
@karlcow see https://github.com/webcompat/devops/issues/10, i "fixed" it with your first suggestion.

**Comment by karlcow** [comment]
```bash
mkdir bar
chmod 444 bar
```

then 

```python
>>> import os
>>> os.makedirs('bar/tmp/foo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/karl/.virtualenvs/shoki/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/Users/karl/.virtualenvs/shoki/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: 'bar/tmp'
```

**Comment by karlcow** [comment]
sent an email to @miketaylr

**Comment by miketaylr** [comment]
Gonna close this since it's fixed. Maybe we can continue discussion in the devops issue.
