### ISSUE TITLE
TypeError on labeler webhook route for staging 

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#1842]
I modified the labeler route to print `body`:

```python
def extract_browser_label(body):
    """Parse the labels from the body in comment:

    <!-- @browser: value -->.
    Currently this only handles a single label,
    because that's all that we set in webcompat.com.
    """
    print(body).encode('utf-8')
    match_list = re.search(r'<!--\s@(\w+):\s([^\d]+?)\s[\d\.]+\s-->', body)
    if match_list:
        # perhaps we do something more interesting depending on
        # what groups(n)[0] is in the future.
        # right now, match_list.groups(0) should look like:
        # ('browser', 'firefox')
        browser = match_list.groups(0)[1].lower()
        browser = browser.translate(None, '()')
        dash_browser = '-'.join(browser.split())
        return 'browser-{name}'.format(name=dash_browser)
    else:
        return None
```

Here's what gets printed:

```
<!-- @browser: Firefox 57.0 -->
<!-- @ua_header: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0 -->
<!-- @reported_with: web -->

**URL**: staging.webcompat.com

**Browser / Version**: Firefox 57.0
**Operating System**: Mac OS X 10.13
**Tested Another Browser**: Yes

**Problem type**: Something else
**Description**: DOES thiS EVEN WORK
**Steps to Reproduce**:

[![Screenshot Description](https://staging.webcompat.com/uploads/2017/10/81e4715c-b4f0-407e-a5b4-2245a23b3061-thumb.jpg)](https://staging.webcompat.com/uploads/2017/10/81e4715c-b4f0-407e-a5b4-2245a23b3061.jpg)



_From [webcompat.com](https://webcompat.com/) with ❤️_
```

Seems OK.

But in the staging-uwsgi.log, we get the following stacktrace:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./webcompat/webhooks/__init__.py", line 44, in hooklistener
    response = new_opened_issue(payload)
  File "./webcompat/webhooks/helpers.py", line 114, in new_opened_issue
    browser_label = extract_browser_label(issue_body)
  File "./webcompat/webhooks/helpers.py", line 31, in extract_browser_label
    browser = browser.translate(None, '()')
TypeError: translate() takes exactly one argument (2 given)
```

And predictably, the webhook results in a 502.

![screen shot 2017-10-13 at 1 43 18 pm](https://user-images.githubusercontent.com/67283/31561136-84f302fc-b01c-11e7-8d7d-f3c497dbc4c1.png)

**Comment by miketaylr** [comment]
But, the labeler webhook is working as expected on production. 😕

**Comment by miketaylr** [comment]
Oh wait.

https://github.com/webcompat/webcompat.com/pull/1812

This is on master, and I deployed milestones. Just need to rebase. :)
