### ISSUE TITLE
Webhooks fail with 500 HTTP error

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1952]
Testing locally.

```
127.0.0.1 - - [04/Dec/2017 14:27:01] "POST /webhooks/labeler HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/karl/code/webcompat.com/webcompat/webhooks/__init__.py", line 47, in hooklistener
    response = new_opened_issue(payload)
  File "/Users/karl/code/webcompat.com/webcompat/webhooks/helpers.py", line 157, in new_opened_issue
    metadata_dict = extract_metadata_labels(issue_body)
NameError: global name 'extract_metadata_labels' is not defined
```

Oooops.

```
    metadata_dict = extract_metadata_labels(issue_body)
NameError: global name 'extract_metadata_labels' is not defined
```

let's see. Rho…

```
→ nosetests
.......................................................................
----------------------------------------------------------------------
Ran 71 tests in 2.266s

OK
```

We have a missing test or a false positive.

See this part 
https://github.com/webcompat/webcompat.com/blob/aba261f71776f35348fedeca63f35eeb1e6667c6/webcompat/webhooks/helpers.py#L20-L31

which is supposed to be called 

https://github.com/webcompat/webcompat.com/blob/aba261f71776f35348fedeca63f35eeb1e6667c6/webcompat/webhooks/helpers.py#L157

but function have changed names? o_0

This commit!
https://github.com/webcompat/webcompat.com/commit/c516370fbdebc0b1e1cc09aaf4ea3551ccb9ce40#diff-53c7dc964488671110b629cf6885fb3e

**Comment by karlcow** [comment]
There is another 500 in there.
https://github.com/webcompat/webcompat.com/blob/aba261f71776f35348fedeca63f35eeb1e6667c6/webcompat/webhooks/__init__.py#L53

This should be

```python
msg = 'failed to set labels on issue {issue}'.format(issue=issue['number'])
```
