### ISSUE TITLE
[bug] 502 Bad Gateway on entering a utf-8 string in URL field.

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#1995]
@softvision-oana-arbuzov found an interesting issue.
1. Go to https://staging.webcompat.com/ 
2.  Enter "價格" in the URL field… and boom.

<img width="778" alt="capture d ecran 2018-01-03 a 22 20 47" src="https://user-images.githubusercontent.com/505230/34522081-5fe375c0-f0d4-11e7-84f8-d7dda2063f27.png">

**Comment by karlcow** [comment]
Additional tests. 

* `é` fails too. So anything which is not ascii. 
* `http://愛.com/` fails too. (which is a problem, it should be converted to http://xn--vgu.com/) aka IDN
* `http://example.com/愛` works.

**Comment by karlcow** [comment]
Ah! good. I was afraid it would be an issue with url parsing and libraries not handling idn, but it seems to be a lot simpler.  We are sometimes a bit loose on strings. We should straighten that or switch to python 3.

```
http://™.com/
127.0.0.1 - - [04/Jan/2018 09:49:19] "POST /issues/new HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/karl/code/webcompat.com/webcompat/views.py", line 227, in create_issue
    response = report_issue(form, proxy=True).json()
  File "/Users/karl/code/webcompat.com/webcompat/issues.py", line 24, in report_issue
    data=json.dumps(build_formdata(form)))
  File "/Users/karl/code/webcompat.com/webcompat/form.py", line 231, in build_formdata
    summary = '{0} - {1}'.format(domain, problem_summary)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2122' in position 0: ordinal not in range(128)
```

**Comment by karlcow** [comment]
https://github.com/webcompat/webcompat.com/blob/58d721512f6cd6bfef351bdaa6ba20e1d2a653a9/webcompat/form.py#L223-L225

form_object returns a unicode string

**Comment by karlcow** [comment]
And just realized we extract twice the url
https://github.com/webcompat/webcompat.com/blob/58d721512f6cd6bfef351bdaa6ba20e1d2a653a9/webcompat/form.py#L241
