### ISSUE TITLE
Fix comments-auth.js

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2108]
Blocks #2106.

**Comment by miketaylr** [comment]
```
✓ firefox on darwin 17.4.0 - Comments (auth) - Comments form visible when logged in (0.608s)
× firefox on darwin 17.4.0 - Comments (auth) - Posting a comment (7.117s)
    AssertionError: Comment was successfully left.
      at Command.<anonymous>  <tests/functional/comments-auth.js:54:13>
      at Test.Posting a comment [as test]  <tests/functional/comments-auth.js:52:12>
      at <src/lib/Test.ts:260:47>

✓ firefox on darwin 17.4.0 - Comments (auth) - Posting an empty comment fails (13.441s)
Error fetching http://localhost:5000/issues/100
× firefox on darwin 17.4.0 - Comments (auth) - Add a screenshot to a comment (15.567s)
    NoSuchElement: [POST http://localhost:4444/wd/hub/session/57e03147-7b74-ac47-b5b4-2868cde0aec5/element / {"using":"css selector","value":".wc-Comment-body"}] Unable to locate element: .wc-Comment-body
    For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
    Build info: version: '3.5.2', revision: '10229a9020', time: '2017-08-21T17:54:21.164Z'
    System info: host: 'omg-5', ip: '192.168.2.83', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.3', java.version: '1.8.0_144'
    Driver info: driver.version: unknown
      at Object.openPage  <tests/functional/lib/helpers.js:27:8>
      at Test.Add a screenshot to a comment [as test]  <tests/functional/comments-auth.js:89:32>
      at <src/lib/Test.ts:260:47>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:36:12>
      at Object.openPage  <tests/functional/lib/helpers.js:29:8>
      at Test.Add a screenshot to a comment [as test]  <tests/functional/comments-auth.js:89:32>
      at <src/lib/Test.ts:260:47>

Error fetching http://localhost:5000/issues/100
✓ firefox on darwin 17.4.0 - Comments (auth) - Pressing 'g' inside of comment textarea *doesn't* go to github issue (15.368s)
Error fetching http://localhost:5000/issues/100
× firefox on darwin 17.4.0 - Comments (auth) - Pressing 'l' inside of comment textarea *doesn't* open the label editor box (15.342s)
    NoSuchElement: [POST http://localhost:4444/wd/hub/session/57e03147-7b74-ac47-b5b4-2868cde0aec5/element / {"using":"css selector","value":".wc-Comment-submit"}] Unable to locate element: .wc-Comment-submit
    For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
    Build info: version: '3.5.2', revision: '10229a9020', time: '2017-08-21T17:54:21.164Z'
    System info: host: 'omg-5', ip: '192.168.2.83', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.3', java.version: '1.8.0_144'
    Driver info: driver.version: unknown
      at Object.openPage  <tests/functional/lib/helpers.js:27:8>
      at Test.Pressing 'l' inside of comment textarea *doesn't* open the label editor box [as test]  <tests/functional/comments-auth.js:129:32>
      at <src/lib/Test.ts:260:47>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:36:12>
      at Object.openPage  <tests/functional/lib/helpers.js:29:8>
      at Test.Pressing 'l' inside of comment textarea *doesn't* open the label editor box [as test]  <tests/functional/comments-auth.js:129:32>
      at <src/lib/Test.ts:260:47>

No unit test coverage for firefox on darwin 17.4.0
firefox on darwin 17.4.0: 3 passed, 3 failed
```

**Comment by miketaylr** [comment]
This is blocked on https://github.com/webcompat/webcompat.com/issues/2092, the last test is failing because commenting is just broken.
