### ISSUE TITLE
Fix history-navigation-non-auth.js

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2109]
```
Error fetching http://localhost:5000/
× firefox on darwin 17.4.0 - History navigation - Back button works from issues page (10.651s)
    NoSuchElement: [POST http://localhost:4444/wd/hub/session/f7b148db-c4c2-cf4d-bfdd-9c7b8b82f4b1/element / {"using":"css selector","value":".js-issues-link"}] Unable to locate element: .js-issues-link
    For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
    Build info: version: '3.5.2', revision: '10229a9020', time: '2017-08-21T17:54:21.164Z'
    System info: host: 'omg-5', ip: '192.168.2.83', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.3', java.version: '1.8.0_144'
    Driver info: driver.version: unknown
      at Object.openPage  <tests/functional/lib/helpers.js:27:8>
      at Test.Back button works from issues page [as test]  <tests/functional/history-navigation-non-auth.js:18:27>
      at <src/lib/Test.ts:260:47>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:36:12>
      at Object.openPage  <tests/functional/lib/helpers.js:29:8>
      at Test.Back button works from issues page [as test]  <tests/functional/history-navigation-non-auth.js:18:27>
      at <src/lib/Test.ts:260:47>
```

**Comment by miketaylr** [comment]
Blocks #2106
