### ISSUE TITLE
Fix image-upload-non-auth.js

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2110]
Blocks #2106.

```
✓ firefox on darwin 17.4.0 - Image Uploads (non-auth) - postMessaged dataURI preview (2.17s)
✓ firefox on darwin 17.4.0 - Image Uploads (non-auth) - postMessaged blob preview (6.5s)
✓ firefox on darwin 17.4.0 - Image Uploads (non-auth) - uploaded image file preview (1.596s)
✓ firefox on darwin 17.4.0 - Image Uploads (non-auth) - postMessaged dataURI image doesn't upload before form submission (1.765s)
✓ firefox on darwin 17.4.0 - Image Uploads (non-auth) - postMessaged blob image doesn't upload before form submission (1.527s)
✓ firefox on darwin 17.4.0 - Image Uploads (non-auth) - uploaded image file doesn't upload before form submission (1.63s)
Error fetching http://localhost:5000/?open=1
× firefox on darwin 17.4.0 - Image Uploads (non-auth) - remove image upload button (10.407s)
    NoSuchElement: [POST http://localhost:4444/wd/hub/session/84faf848-424a-9049-82af-a7766c86da5d/element / {"using":"css selector","value":".remove-upload"}] Unable to locate element: .remove-upload
    For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
    Build info: version: '3.5.2', revision: '10229a9020', time: '2017-08-21T17:54:21.164Z'
    System info: host: 'omg-5', ip: '192.168.2.83', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.3', java.version: '1.8.0_144'
    Driver info: driver.version: unknown
      at Object.openPage  <tests/functional/lib/helpers.js:27:8>
      at Test.remove image upload button [as test]  <tests/functional/image-uploads-non-auth.js:138:27>
      at <src/lib/Test.ts:260:47>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:36:12>
      at Object.openPage  <tests/functional/lib/helpers.js:29:8>
      at Test.remove image upload button [as test]  <tests/functional/image-uploads-non-auth.js:138:27>
      at <src/lib/Test.ts:260:47>

Error fetching http://localhost:5000/?open=1
× firefox on darwin 17.4.0 - Image Uploads (non-auth) - double image select works (10.404s)
    NoSuchElement: [POST http://localhost:4444/wd/hub/session/84faf848-424a-9049-82af-a7766c86da5d/element / {"using":"css selector","value":".remove-upload"}] Unable to locate element: .remove-upload
    For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
    Build info: version: '3.5.2', revision: '10229a9020', time: '2017-08-21T17:54:21.164Z'
    System info: host: 'omg-5', ip: '192.168.2.83', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.3', java.version: '1.8.0_144'
    Driver info: driver.version: unknown
      at Object.openPage  <tests/functional/lib/helpers.js:27:8>
      at Test.double image select works [as test]  <tests/functional/image-uploads-non-auth.js:178:32>
      at <src/lib/Test.ts:260:47>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:36:12>
      at Object.openPage  <tests/functional/lib/helpers.js:29:8>
      at Test.double image select works [as test]  <tests/functional/image-uploads-non-auth.js:178:32>
      at <src/lib/Test.ts:260:47>
```

**Comment by magsout** [comment]
@miketaylr What I have done:

https://gist.github.com/magsout/3d2cb9d61feea65367039c5afb0b5258/revisions

But I don't understand the last error:

```
× firefox on darwin 17.3.0 - Image Uploads (non-auth) - remove image upload button
AssertionError: Remove button is displayed: expected false to equal true
```

For me the selector is ok and should be working

```
.findByCssSelector(".js-image-upload .js-remove-upload")
          .isDisplayed()
          .then(function(isDisplayed) {
            assert.equal(isDisplayed, true, "Remove button is displayed");
          })
          .end()
```

thought?

**Comment by miketaylr** [comment]
@magsout if you try the following in the console:

`postMessage("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABkAAAAZCAIAAABLixI0AAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAB3RJTUUH3gYSAig452t/EQAAAClJREFUOMvtzkENAAAMg0A25ZU+E032AQEXoNcApCGFLX5paWlpaWl9dqq9AS6CKROfAAAAAElFTkSuQmCC", "http://localhost:5000")`

(what the test does)

You can see the remove button is not displayed.... so something broke here. 😕 Let me look in bugform.js.

**Comment by miketaylr** [comment]
@magsout I think it's something to do with 

```
.label-remove {
  visibility: hidden;
}
```

In ` this.showRemoveUpload`, we do `removeBanner.removeClass("is-hidden");`, but it has that `label-remove` class. So it's still hidden after that? Confusing to me that it works if you click on the upload thing manually.

But, we need to fix this -- otherwise Firefox users won't be able to remove screenshots. Let me know if you get stuck trying to figure this out.

**Comment by magsout** [comment]
@miketaylr even if postMessage manualy the postMessage, I get this:

![capture d ecran 2018-02-19 a 09 04 27](https://user-images.githubusercontent.com/1997108/36367814-ad086104-1554-11e8-8c2d-9a24ce7a9713.png)

![capture d ecran 2018-02-19 a 09 04 32](https://user-images.githubusercontent.com/1997108/36367818-b1592b1c-1554-11e8-9ac4-2f63b5fa7370.png)

![capture d ecran 2018-02-19 a 09 04 37](https://user-images.githubusercontent.com/1997108/36367824-b5fe7f00-1554-11e8-9613-5cf160b78b4a.png)

![capture d ecran 2018-02-19 a 09 09 18](https://user-images.githubusercontent.com/1997108/36367827-b8e9c2f6-1554-11e8-95e4-df9669186c2c.png)

The element is visible (I removed the `.label-remove` class) and test is still faling.

So Yes I get stuck :(

**Comment by miketaylr** [comment]
> So Yes I get stuck :(

Let me steal this, I have a few hours. ❤️
