### ISSUE TITLE
Fix reporting-auth.js

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2119]
Blocks #2106.

```
Error fetching http://localhost:5000/issues/new
× firefox on darwin 17.4.0 - Reporting (auth) - Report button shows name (10.496s)
    NoSuchElement: [POST http://localhost:4444/wd/hub/session/9a63d237-aef1-c842-839c-9ebdd7c69801/element / {"using":"css selector","value":".js-Navbar-link"}] Unable to locate element: .js-Navbar-link
    For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
    Build info: version: '3.5.2', revision: '10229a9020', time: '2017-08-21T17:54:21.164Z'
    System info: host: 'omg-5', ip: '192.168.2.83', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.3', java.version: '1.8.0_144'
    Driver info: driver.version: unknown
      at Object.openPage  <tests/functional/lib/helpers.js:27:8>
      at Test.Report button shows name [as test]  <tests/functional/reporting-auth.js:25:32>
      at <src/lib/Test.ts:260:47>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:36:12>
      at Object.openPage  <tests/functional/lib/helpers.js:29:8>
      at Test.Report button shows name [as test]  <tests/functional/reporting-auth.js:25:32>
      at <src/lib/Test.ts:260:47>

TOTAL: tested 1 platforms, 0 passed, 1 failed

```

**Comment by miketaylr** [comment]
This got fixed... by something else.
