### ISSUE TITLE
Catch `requests.exceptions.ConnectionError` when submiting bug form 

### ISSUE THREAD

**Issue by zoepage** [webcompat/webcompat.com#2292]
When you have connectivity issues while submitting the bug form, we get `requests.exceptions.ConnectionError`
<img width="1383" alt="screen shot 2018-03-23 at 1 54 51 pm" src="https://user-images.githubusercontent.com/562354/37830112-cb360012-2ea1-11e8-800a-9f444a869fd7.png">

**Comment by karlcow** [comment]
@zoepage nice find, never seen this one. Could you give a bit more of the context of the issue? Do you remember if the network went down or something similar? Did it take a while before displaying the message?

The top error message from your screenshot 

* ConnectionError: 
* `HTTPSConnnectionPool(host='api.github.com', port=443)`
* Max retries exceeded with url: `/repos/webcompat/webcompat-tests/issues`
* (Cause by NewConnectionError(`<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10875f090>:`)
* Failed to establish a new connection: `[Errno 8] nodename nor servname provided, or not known',`))

hmmm… thinking…  I wonder if it's a question of exceeded quota. 
@zoepage if you are sure that was the network that would not be it, but if you are not sure it could be the server saying "no more requests".

…

ah… maybe not. Let's see. 

```python
>>> import requests
>>> requests.get('https://INeedATeurgouleToday.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ineedateurgouletoday.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10d542ad0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
```

and 

```bash
whois INeedATeurgouleToday.com
No match for domain "INEEDATEURGOULETODAY.COM".
```

So non-existent dns or failed dns resolution.

Let's try with the network down too. Same error message with the network down. 

## Steps to reproduce
1. Start the project with the network on.
2. login (probably optional)
3. Go to http://localhost:5000/issues/new
4. Cut the network
5. Fill the form and submit. 

Error message:

```
requests.exceptions.ConnectionError

ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/webcompat/webcompat-tests/issues (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1052821d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
Traceback (most recent call last)

    File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__

    return self.wsgi_app(environ, start_response)

    File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app

    response = self.handle_exception(e)

    File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app

    response = self.full_dispatch_request()

    File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception

    reraise(exc_type, exc_value, tb)

    File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request

    rv = self.dispatch_request()

    File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

    File "/Users/karl/code/webcompat.com/webcompat/views.py", line 221, in create_issue

    response = report_issue(form)

    File "/Users/karl/code/webcompat.com/webcompat/issues.py", line 26, in report_issue

    return github.post(path, build_formdata(form))

    File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask_github.py", line 280, in post

    data=data, **kwargs)

    File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask_github.py", line 244, in request

    response = self.raw_request(method, resource, **kwargs)

    File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask_github.py", line 233, in raw_request

    return self.session.request(method, url, allow_redirects=True, **kwargs)

    File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/requests/sessions.py", line 488, in request

    resp = self.send(prep, **send_kwargs)

    File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/requests/sessions.py", line 609, in send

    r = adapter.send(request, **kwargs)

    File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/requests/adapters.py", line 487, in send

    raise ConnectionError(e, request=request)

    ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/webcompat/webcompat-tests/issues (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1052821d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

```

Entering in the interactive debugging mode.

<img width="917" alt="capture d ecran 2018-03-26 a 08 35 13" src="https://user-images.githubusercontent.com/505230/37881290-b2763b60-30d0-11e8-82cc-084655ff6968.png">

We could probably wrap the `response = report_issue(form)` in views.py in a `try` statement. At least we can catch the error gracefully and sends a flash message showing "It seems there are connection issues at the moment with your device" (or something with a better prose).

Trying to imagine what is happening next. The flash message is shown, nothing has moved and we don't want to redirect anywhere. 

ok… I tried this as a prototype and it didn't explode. There are missing pieces.

```python
    if form.get('submit-type') == AUTH_REPORT:
        if g.user:  # If you're already authed, submit the bug.
            try:
                response = report_issue(form)
                session['show_thanks'] = True
                return redirect(url_for('show_issue',
                                        number=response.get('number')))
            except Exception as e:
                print("foo", e)
            else:
                pass
        else:  # Stash form data into session, go do GitHub auth
            session['form_data'] = form
            return redirect(url_for('login'))
    elif form.get('submit-type') == PROXY_REPORT:
        response = report_issue(form, proxy=True).json()
        session['show_thanks'] = True
        return redirect(url_for('show_issue', number=response.get('number')))
    else:
        # if anything wrong, we assume it is a bad forged request
        abort(400)
```

but then that would not solve the other cases: "Report as anonymous" and the "Github Auth dance" cases.

We can repeat the try statement but that seems to be overkill. Maybe changing a bit this piece of code is working.

I was wondering also if listening on online, offline events through `window.navigator.onLine;` could work. I think I remember that @zoepage was giving talks about offline first. Do you know if it would make to deactivate the submit button with a message if network is off.
