### ISSUE TITLE
403 when trying to "delete" changelog issue label

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2330]
```
🐓 python tools/changelog.py -d
Statuses Initialization…
Fetching milestones from Github…
Milestones saved in data/
Milestones in memory


## X.X.X - 2018-03-28

* Fixes #2215 - Tweaks needinfo filtering and design [Pull #2290](https://api.github.com/repos/webcompat/webcompat.com/issues/2290)
* Fixes issue #2203 UnboundLocalError on milestones_content [Pull #2221](https://api.github.com/repos/webcompat/webcompat.com/issues/2221)
* Refactor isReportableURL function [Pull #2220](https://api.github.com/repos/webcompat/webcompat.com/issues/2220)
* Fixes #2193: Add support for --grep when running intern tests. [Pull #2194](https://api.github.com/repos/webcompat/webcompat.com/issues/2194)
* Fixes #740 - Adds tool to create changelog. [Pull #2105](https://api.github.com/repos/webcompat/webcompat.com/issues/2105)



Deleting "status: add to changelog" for 2290 on webcompat.com…
403 for issue 2290
Deleting "status: add to changelog" for 2221 on webcompat.com…
403 for issue 2221
Deleting "status: add to changelog" for 2220 on webcompat.com…
403 for issue 2220
Deleting "status: add to changelog" for 2194 on webcompat.com…
403 for issue 2194
Deleting "status: add to changelog" for 2105 on webcompat.com…
403 for issue 2105

```

cc @karlcow

**Comment by karlcow** [comment]
huh? 👺 
@miketaylr 
* Was it the first time it happens? Or was it the first time you tried `-d`?
* And are you inside the environment before using it? It requires credentials to delete. If it's the case, I should introduce a test to see if the user has the right credentials.

**Comment by miketaylr** [comment]
> Was it the first time it happens? Or was it the first time you tried -d?

This is the first time I tried -d, I think. I've used it 3 total times now, but just removed labels by hand (because I forgot... :P)

> And are you inside the environment before using it?

Yes, I was. You can see I'm in my "(webcompat)" virtual environment.

<img width="987" alt="screen shot 2018-03-29 at 10 32 44 am" src="https://user-images.githubusercontent.com/67283/38098038-90602a22-333c-11e8-8c28-e50a72e6786d.png">

**Comment by karlcow** [comment]
```
🐝 09:42:25 ~/code/webcompat.com
→ python tools/changelog.py -t -d
Statuses Initialization…
Fetching milestones from Github…
Milestones saved in data/
Milestones in memory


## X.X.X - 2018-04-06

* candy.de - design is broken [Pull #1458](https://github.com/webcompat/webcompat-tests/issues/1458)
* gfjhgfjh - design is broken [Pull #1381](https://github.com/webcompat/webcompat-tests/issues/1381)



Deleting "status: add to changelog" for 1458 on webcompat-tests…
200 for issue 1458
Deleting "status: add to changelog" for 1381 on webcompat-tests…
200 for issue 1381
```

This is working in test without changing anything.

hmm…
This is what I get with a print(url) and blocking the actual delete.

## Test version
```
🐝 09:48:57 ~/code/webcompat.com
→ python tools/changelog.py -d -t
Statuses Initialization…
Fetching milestones from Github…
Milestones saved in data/
Milestones in memory


## X.X.X - 2018-04-06

* candy.de - design is broken [Pull #1458](https://github.com/webcompat/webcompat-tests/issues/1458)
* gfjhgfjh - design is broken [Pull #1381](https://github.com/webcompat/webcompat-tests/issues/1381)



Deleting "status: add to changelog" for 1458 on webcompat-tests…
https://api.github.com/repos/webcompat/webcompat-tests/issues/1458/labels/status: add to changelog
foo for issue 1458
Deleting "status: add to changelog" for 1381 on webcompat-tests…
https://api.github.com/repos/webcompat/webcompat-tests/issues/1381/labels/status: add to changelog
foo for issue 1381
```

## production version

```
🐝 09:48:16 ~/code/webcompat.com
→ python tools/changelog.py -d
Statuses Initialization…
Fetching milestones from Github…
Milestones saved in data/
Milestones in memory


## X.X.X - 2018-04-06

* Fixes #2360 - Add blockquote styles [Pull #2366](https://github.com/webcompat/webcompat.com/pull/2366)
* Fixes #2225 - Add stylelint-order. Fix ordering in CSS src files [Pull #2365](https://github.com/webcompat/webcompat.com/pull/2365)
* Issue #2303. Add some styling to login + keyboard hints. [Pull #2363](https://github.com/webcompat/webcompat.com/pull/2363)
* Issue #2271. Use a regular expression to get image upload data URI. [Pull #2362](https://github.com/webcompat/webcompat.com/pull/2362)
* Fixes #2358 - Inline code multiline wrap on issue template [Pull #2361](https://github.com/webcompat/webcompat.com/pull/2361)
* fixes #2356 - fixed result when older < needsinfo [Pull #2357](https://github.com/webcompat/webcompat.com/pull/2357)
* Fixes #2300. Try to respect DNT preference before talking to GA. [Pull #2353](https://github.com/webcompat/webcompat.com/pull/2353)



Deleting "status: add to changelog" for 2366 on webcompat.com…
https://api.github.com/repos/webcompat/webcompat.com/issues/2366/labels/status: add to changelog
foo for issue 2366
Deleting "status: add to changelog" for 2365 on webcompat.com…
https://api.github.com/repos/webcompat/webcompat.com/issues/2365/labels/status: add to changelog
foo for issue 2365
Deleting "status: add to changelog" for 2363 on webcompat.com…
https://api.github.com/repos/webcompat/webcompat.com/issues/2363/labels/status: add to changelog
foo for issue 2363
Deleting "status: add to changelog" for 2362 on webcompat.com…
https://api.github.com/repos/webcompat/webcompat.com/issues/2362/labels/status: add to changelog
foo for issue 2362
Deleting "status: add to changelog" for 2361 on webcompat.com…
https://api.github.com/repos/webcompat/webcompat.com/issues/2361/labels/status: add to changelog
foo for issue 2361
Deleting "status: add to changelog" for 2357 on webcompat.com…
https://api.github.com/repos/webcompat/webcompat.com/issues/2357/labels/status: add to changelog
foo for issue 2357
Deleting "status: add to changelog" for 2353 on webcompat.com…
https://api.github.com/repos/webcompat/webcompat.com/issues/2353/labels/status: add to changelog
foo for issue 2353
```

@miketaylr Does it work for you when you use the `-t` flag.

**Comment by miketaylr** [comment]
> @miketaylr Does it work for you when you use the `-t` flag.

oops. missed this.

Right now there's possibly a different bug:

```
python tools/changelog.py -d -t
Writing logs to: /Users/mitaylor/dev/webcompat.com/tmp
Statuses Initialization…
Milestones in memory
Traceback (most recent call last):
  File "tools/changelog.py", line 127, in <module>
    sys.exit(main())
  File "tools/changelog.py", line 107, in main
    loglines = create_changelog(json_response)
  File "tools/changelog.py", line 54, in create_changelog
    title = normalize_title(issue['title'])
  File "tools/changelog.py", line 75, in normalize_title
    title = 'Fixes #{msg[number]} - {msg[prose]}'.format(msg=m.groupdict())
AttributeError: 'NoneType' object has no attribute 'groupdict'
```

capturing the issues to document a potential bug (maybe the `/`?)

<img width="777" alt="screen shot 2018-09-24 at 6 54 08 pm" src="https://user-images.githubusercontent.com/67283/45985310-47786780-c02b-11e8-9031-f1bada302587.png">
