### ISSUE TITLE
[changelog.py] UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 12: ordinal not in range(128)

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2430]
```
🐓 python tools/changelog.py 
Statuses Initialization…
Fetching milestones from Github…
Milestones saved in data/
Milestones in memory
Traceback (most recent call last):
  File "tools/changelog.py", line 114, in <module>
    sys.exit(main())
  File "tools/changelog.py", line 94, in main
    loglines = create_changelog(json_response)
  File "tools/changelog.py", line 56, in create_changelog
    loglines += LINE_TEMPLATE.format(title=title, url=url, number=number)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 12: ordinal not in range(128)
```

It looks like https://github.com/webcompat/webcompat.com/pull/2423 is the culprit here:

`Fixes #2346 – Update eslint and prettier packages. Format JS files` the long dash is `\u2013`.

**Comment by miketaylr** [comment]
(i'm gonna just change that title because i'm lazy, in case someone investigates later and is confused)

**Comment by karlcow** [comment]
🤔 So this has been handled in #2431 through #2433 
There's one issue though if we start the prose after the separator with a non-ascii word.

* This fails: `'Fixes #101 - 愛 is love.'` 
* This works: `'Fixes #101 - all we need is 愛.'`

I can introduce matching in the regex against any kind of unicode but then it becomes a tad more complicated for handling the separators.

@miketaylr So if you are ok with the normalization in #2433 We can close this one.

**Comment by miketaylr** [comment]
@karlcow SGTM!
