### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '.../webcompat.com/tmp/webcompat.log'

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#2515]
Noticed by @laghee in https://github.com/webcompat/webcompat.com/pull/2513.

```
Traceback (most recent call last):
  File "run.py", line 35, in <module>
    from webcompat import app
  File "/home/travis/build/webcompat/webcompat.com/webcompat/__init__.py", line 44, in <module>
    file_handler = logging.FileHandler(app.config['LOG_FILE'])
  File "/opt/python/2.7.14/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/python/2.7.14/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/home/travis/build/webcompat/webcompat.com/tmp/webcompat.log'
```

I'm guessing if you don't have a `/tmp/` it blows up, so we should create it.

**Comment by miketaylr** [comment]
```
🐓 rm -rf tmp/
mitaylor at omg-5 in ~/dev/webcompat.com on master
🐓 source env/bin/activate
(env) mitaylor at omg-5 in ~/dev/webcompat.com on master
🐓 python run.py 
Writing logs to: /Users/mitaylor/dev/webcompat.com/tmp
Statuses Initialization…
Fetching milestones from Github…
Milestones saved in data/
Milestones in memory
Traceback (most recent call last):
  File "run.py", line 35, in <module>
    from webcompat import app
  File "/Users/mitaylor/dev/webcompat.com/webcompat/__init__.py", line 44, in <module>
    file_handler = logging.FileHandler(app.config['LOG_FILE'])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 911, in __init__
    StreamHandler.__init__(self, self._open())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 941, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/Users/mitaylor/dev/webcompat.com/tmp/webcompat.log'
```

**Comment by miketaylr** [comment]
Regressed by #2501.
