### ISSUE TITLE
big console.log input are truncated

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2716]
Also another big problem 😨 
in https://github.com/webcompat/web-bugs/issues/21657
We can see that the string is truncated. We need to figure out if the truncation happens on webcompat.com side or on the reporter side.

The truncation happens at 7947 chars.

I wonder if it's the input hidden field storage which is reaching a limit.

**Comment by karlcow** [comment]
I created a test with 10000 chars long string in details.
And it worked whichever the limit is I didn't reach it. 
https://github.com/webcompat/webcompat-tests/issues/1722

So the truncated dictionary might be another issue. I wonder if we should test the integrity of what we received from the POST before posting it.

**Comment by karlcow** [comment]
Let's try with a detail value which is 1.490.017 characters long. Ah I crashed it.

```
127.0.0.1 - - [22/Nov/2018 11:00:57] "POST /issues/new HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/karl/code/webcompat.com/webcompat/views.py", line 248, in create_issue
    url_for('show_issue', number=json_response.get('number')))
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'show_issue'. Did you forget to specify values ['number']?
```

**Comment by karlcow** [comment]
But I wonder if it's because GitHub is telling us. no no no. Too heavy.

**Comment by karlcow** [comment]
Ah bingo. That doesn't explain the truncation we got for the logs but that shows another limit that we should test. Any POST data which is too big aka more than 65536 characters will fail. 

```
>>> json_response
{u'documentation_url': u'https://developer.github.com/v3/issues/#create-an-issue', u'message': u'Validation Failed', u'errors': [{u'field': u'body', u'message': u'body is too long (maximum is 65536 characters)', u'code': u'custom', u'resource': u'Issue'}]}
```

We need to handle this.
so we do not end up in a 500. Opening a new issue.

**Comment by karlcow** [comment]
Opened #2717 for the too big body.

**Comment by karlcow** [comment]
so we don't seem to have a limit issue with regards to the forms. aka the form handled it and tried to send it to GitHub.
so now my eyes are going into the direction of @wisniewskit  👀
I wonder if there is a truncation happening before.

**Comment by karlcow** [comment]
(paper trail) Opened https://bugzilla.mozilla.org/show_bug.cgi?id=1510063 for the truncation

**Comment by wisniewskit** [comment]
@karlcow, I just took another look at the truncated issue, and I actually see the full console log of 27328 characters appearing on https://webcompat.com/issues/21657 (just not on the github.com version of the same page).

Perhaps it's another limit github imposes, as per #2717 ?

**Comment by karlcow** [comment]
Ooooh that's interesting! So I guess there is a character which is tripping up the rendering on github and I was fooled by this. All content from webcompat.com is coming from GitHub. Let's see.

1. Rendered version on webcompat.com of the GitHub data. (end of the string)

<img width="730" alt="capture d ecran 2018-11-28 a 06 25 45" src="https://user-images.githubusercontent.com/505230/49112580-7e425680-f2d6-11e8-85d2-9a9cd0a343a8.png">

2. Rendered version on github.com of the GitHub data (end of the string)

<img width="726" alt="capture d ecran 2018-11-28 a 06 27 24" src="https://user-images.githubusercontent.com/505230/49112656-b0ec4f00-f2d6-11e8-9704-9f77e7a3671e.png">

3. Raw data version on github.com of the GitHub data (end of the string) once we clicked "edit"

<img width="740" alt="capture d ecran 2018-11-28 a 06 28 56" src="https://user-images.githubusercontent.com/505230/49112750-ebee8280-f2d6-11e8-8cbf-6bbb05bebf81.png">


ok the full content is there. I will close this here, as it is a bug in the renderer of GitHub and doesn't affect webcompat.com.

Thanks a lot @wisniewskit !!!
