### ISSUE TITLE
`npm run start:test` is not working with virtualenvwrapper

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2736]
Be with environment already started.

```
14:58:36 ~/code/webcompat.com
→ workon webcompatcom
🐝 14:58:45 ~/code/webcompat.com
→ npm run start:test

> webcompat@ start:test /Users/karl/code/webcompat.com
> npm run build && source env/bin/activate || . env/bin/activate && python run.py -t


> webcompat@ build /Users/karl/code/webcompat.com
> grunt

Running "checkDependencies:default" (checkDependencies) task

Running "jst:compile" (jst) task
File webcompat/static/js/dist/templates.js created.

Running "concat:dist" (concat) task

Running "concat:untriaged" (concat) task

Running "concat:issues" (concat) task

Running "concat:issueList" (concat) task

Running "concat:userActivity" (concat) task

Running "uglify:dist" (uglify) task
>> 1 file created 573.2 kB → 392.36 kB

Running "uglify:ga" (uglify) task
>> 1 file created 780 B → 585 B

Running "uglify:issues" (uglify) task
>> 1 file created 51.15 kB → 28.35 kB

Running "uglify:issueList" (uglify) task
>> 1 file created 38.84 kB → 20.6 kB

Running "uglify:userActivity" (uglify) task
>> 1 file created 22.23 kB → 11.61 kB

Running "uglify:untriaged" (uglify) task
>> 1 file created 14.08 kB → 7.06 kB

Running "uglify:contributors" (uglify) task
>> 1 file created 1.1 kB → 733 B

Running "postcss:dist" (postcss) task
>> 1 processed stylesheet created.

Running "cssmin:combine" (cssmin) task
>> 1 file created. 1.87 kB → 38.47 kB

Done.
sh: env/bin/activate: No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webcompat@ start:test: `npm run build && source env/bin/activate || . env/bin/activate && python run.py -t`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webcompat@ start:test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/karl/.npm/_logs/2018-12-13T05_58_57_264Z-debug.log

🐝 14:58:57 ~/code/webcompat.com
→ more /Users/karl/.npm/_logs/2018-12-13T05_58_57_264Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/Users/karl/.nvm/versions/node/v9.10.0/bin/node',
1 verbose cli   '/Users/karl/.nvm/versions/node/v9.10.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start:test' ]
2 info using npm@6.4.1
3 info using node@v9.10.0
4 verbose run-script [ 'prestart:test', 'start:test', 'poststart:test' ]
5 info lifecycle webcompat@~prestart:test: webcompat@
6 info lifecycle webcompat@~start:test: webcompat@
7 verbose lifecycle webcompat@~start:test: unsafe-perm in lifecycle true
8 verbose lifecycle webcompat@~start:test: PATH: (Commenting out my $PATH)
9 verbose lifecycle webcompat@~start:test: CWD: /Users/karl/code/webcompat.com
10 silly lifecycle webcompat@~start:test: Args: [ '-c',
10 silly lifecycle   'npm run build && source env/bin/activate || . env/bin/activate && python run.py -t' ]
11 silly lifecycle webcompat@~start:test: Returned: code: 1  signal: null
12 info lifecycle webcompat@~start:test: Failed to exec start:test script
13 verbose stack Error: webcompat@ start:test: `npm run build && source env/bin/activate || . env/bin/activate && python run.py -t`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/karl/.nvm/versions/node/v9.10.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/karl/.nvm/versions/node/v9.10.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid webcompat@
15 verbose cwd /Users/karl/code/webcompat.com
16 verbose Darwin 18.2.0
17 verbose argv "/Users/karl/.nvm/versions/node/v9.10.0/bin/node" "/Users/karl/.nvm/versions/node/v9.10.0/bin/npm" "run" "start:test"
18 verbose node v9.10.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error webcompat@ start:test: `npm run build && source env/bin/activate || . env/bin/activate && python run.py -t`
22 error Exit status 1
23 error Failed at the webcompat@ start:test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

OR NOT

```
🐝 15:01:50 ~/code/webcompat.com
→ deactivate
15:01:55 ~/code/webcompat.com
→ npm run start:test

> webcompat@ start:test /Users/karl/code/webcompat.com
> npm run build && source env/bin/activate || . env/bin/activate && python run.py -t


> webcompat@ build /Users/karl/code/webcompat.com
> grunt

Running "checkDependencies:default" (checkDependencies) task

Running "jst:compile" (jst) task
File webcompat/static/js/dist/templates.js created.

Running "concat:dist" (concat) task

Running "concat:untriaged" (concat) task

Running "concat:issues" (concat) task

Running "concat:issueList" (concat) task

Running "concat:userActivity" (concat) task

Running "uglify:dist" (uglify) task
>> 1 file created 573.2 kB → 392.36 kB

Running "uglify:ga" (uglify) task
>> 1 file created 780 B → 585 B

Running "uglify:issues" (uglify) task
>> 1 file created 51.15 kB → 28.35 kB

Running "uglify:issueList" (uglify) task
>> 1 file created 38.84 kB → 20.6 kB

Running "uglify:userActivity" (uglify) task
>> 1 file created 22.23 kB → 11.61 kB

Running "uglify:untriaged" (uglify) task
>> 1 file created 14.08 kB → 7.06 kB

Running "uglify:contributors" (uglify) task
>> 1 file created 1.1 kB → 733 B

Running "postcss:dist" (postcss) task
>> 1 processed stylesheet created.

Running "cssmin:combine" (cssmin) task
>> 1 file created. 1.87 kB → 38.47 kB

Done.
sh: env/bin/activate: No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webcompat@ start:test: `npm run build && source env/bin/activate || . env/bin/activate && python run.py -t`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webcompat@ start:test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/karl/.npm/_logs/2018-12-13T06_02_21_606Z-debug.log
```

The reason is that in my configuration I do not have a local `env/` 

my virtualenv is elsewhere. 

```
15:02:21 ~/code/webcompat.com
→ ls -al ~/.virtualenvs/webcompatcom/
total 32
drwxr-xr-x  10 karl  staff   320 12 avr  2018 .
drwxr-xr-x  47 karl  staff  1504  3 oct 16:57 ..
-rw-r--r--@  1 karl  staff  6148 26 jui  2017 .DS_Store
lrwxr-xr-x   1 karl  staff    63 27 jan  2017 .Python -> /System/Library/Frameworks/Python.framework/Versions/2.7/Python
-rw-r--r--   1 karl  staff    31 27 jan  2017 .project
drwxr-xr-x  52 karl  staff  1664  9 aoû 15:57 bin
drwxr-xr-x   3 karl  staff    96 26 mar  2014 include
drwxr-xr-x   3 karl  staff    96 26 mar  2014 lib
drwxr-xr-x   3 karl  staff    96 12 avr  2018 man
-rw-r--r--   1 karl  staff    59  9 aoû 13:04 pip-selfcheck.json
```

aka in `~/.virtualenvs/webcompatcom/`

This is the result of `virtualenvwrapper`.

I will probably fix my environment BUT I want to better understand

```
    "start:test": "npm run build && source env/bin/activate || . env/bin/activate && python run.py -t",
```
it doesn't seem logical. Or should I read it as 
`npm run build && (source env/bin/activate || . env/bin/activate) && python run.py -t`

We can probably make package.json a bit more DRY.

**Comment by marimeireles** [comment]
Humm
Doesn't  `source env/bin/activate` and `. env/bin/activate` do the same thing?
I think `(npm run build && source env/bin/activate) || (. env/bin/activate && python run.py) -t` makes more sense... Because we can either use npm or python to run the script, right?

**Comment by karlcow** [comment]
yes they do the same thing. It's one or the other depending on the platform, hence my parenthesis. 

1. `npm run build` -> this is for grunt
2. `$SHELL_SOURCE env/bin/activate` -> start the python virtual environment
3. `python run.py -t` -> start the app in testing mode

step 2 is failing for me because I use `virtualenvwrapper`, I think @miketaylr  is using something else. [buritto](https://github.com/brainsik/virtualenv-burrito)? which basically install the same thing than mine (and breaks the `npm run` commands in `package.json`).

**Comment by miketaylr** [comment]
> I think @miketaylr is using something else. [buritto](https://github.com/brainsik/virtualenv-burrito)?

Not anymore. I nuked that a while ago when I got a new laptop.

**Comment by karlcow** [comment]
Let me close this, as the code is working if you follow the guide and do not have exotic install ;)
