### ISSUE TITLE
firehose creates an issue for webcompat under python3

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#2892]
Related to #2348 

```
OSError: write error
Traceback (most recent call last):
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 2087, in preprocess_request
    rv = func()
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask_firehose.py", line 76, in populate
    pushed_items = self.connector.get_pushed()
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask_firehose.py", line 18, in get_pushed
    return set(pushed_items.split(','))
TypeError: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 2087, in preprocess_request
    rv = func()
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask_firehose.py", line 76, in populate
    pushed_items = self.connector.get_pushed()
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask_firehose.py", line 18, in get_pushed
    return set(pushed_items.split(','))
TypeError: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 2087, in preprocess_request
    rv = func()
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask_firehose.py", line 76, in populate
    pushed_items = self.connector.get_pushed()
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask_firehose.py", line 18, in get_pushed
    return set(pushed_items.split(','))
TypeError: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 2087, in preprocess_request
    rv = func()
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask_firehose.py", line 76, in populate
    pushed_items = self.connector.get_pushed()
  File "/home/webcompat/py3.webcompat.com/env/lib/python3.7/site-packages/flask_firehose.py", line 18, in get_pushed
    return set(pushed_items.split(','))
TypeError: a bytes-like object is required, not 'str'
```

**Comment by karlcow** [comment]
We introduced Firehose in #2778 and it is related to this project 
https://github.com/shreyanshk/flask-firehose
We need to figure out why it fails, but probably a string/bytes conversion of some sort.

**Comment by karlcow** [comment]
@marimeireles Do you remember why you put into comments the firehose.init_app()

https://github.com/webcompat/webcompat.com/blob/d2064e6cbcc01a8fcddc646fc09e83464eaf95c0/webcompat/__init__.py#L17-L22

**Comment by karlcow** [comment]
```
announcing my loyalty to the Emperor...
announcing my loyalty to the Emperor...
/js/dist/webcompat.min.js?69c597a662bade7032f08403480e5552,/img/svg/icons/svg-leaf_left.svg,/css/dist/webcompat.min.css,/img/svg/icons/svg-leaf_right.svg <class 'str'>
```

ok understood. 

we need to push bytes not string.

https://github.com/webcompat/webcompat.com/blob/d2064e6cbcc01a8fcddc646fc09e83464eaf95c0/webcompat/views.py#L156-L170

**Comment by karlcow** [comment]
Interesting too, depending on me using two different browsers I get different results. 
Working in nightly and not in dev edition for me. 

I need to figure out why.

**Comment by marimeireles** [comment]
> @marimeireles Do you remember why you put into comments the firehose.init_app()

Yes. Without it we're not able to push things as HTTP2.

Hmm I'm going to have a look at this too, to see if I can help with something.

> Interesting too, depending on me using two different browsers I get different results.
Working in nightly and not in dev edition for me.

Are you getting this error even after pushing stuff as bytes instead of strings?

**Comment by marimeireles** [comment]
Oh!
I think I know what it is! This lib was originally written to use with python3 systems. I had to write a different code than the one recommended by firehose's docs.

So instead of writing:

```
 push('/css/dist/webcompat.min.css', **{ 
     'as': 'style', 
     'rel': 'preload' 
 }) 
```

You can try:
```
 push('/css/dist/webcompat.min.css', rel='preload') 
```

I think I had to do that because rel was a reserved word on python2? Something like that, it wouldn't work if I wrote exactly like the docs said I had to.

@karlcow let me know if it works :)

**Comment by karlcow** [comment]
I'll check that on thursday. Thanks a lot @marimeireles

**Comment by karlcow** [comment]
>  Working in nightly and not in dev edition for me.

This is solved when deleting the cookies (probably from the previous version)
On nightly I was starting with a fresh profile always. On dev edition I had a cookie.

Was it the same for you @miketaylr ?

**Comment by karlcow** [comment]
I do not get the error message anymore.
so we got a staging python3 site.

**Comment by miketaylr** [comment]
Yep! Working now, after I deleted the session cookie. That feels like a bug... ideally the server would just evict the session / destroy the cookie. Will this affect all the previous visitors to webcompat.com production once we switch over to Python 3?

**Comment by miketaylr** [comment]
@karlcow WDYT? Should we open a new bug to investigate / track this before we ship Python 3 to production? 

I think we would just need to make sure we invalidate all existing sessions when we switch over, which can be done by changing the session secret key:

https://github.com/pallets/flask/issues/1574#issuecomment-143781767
https://stackoverflow.com/questions/27747578/how-do-i-clear-a-flask-session#comment74939289_27764937

**Comment by karlcow** [comment]
@miketaylr I think we had a similar bug in the past. Yeah… #1818 and #1327 and 
This is also related #672 (this one is open)

Probably there is a documentation item to write down here. **if you touch sessions DB, change the APP secret key**.
