### ISSUE TITLE
security updates from Github breaks changelog

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#3015]
PR #3013 breaks the changelog tool.

```
% python3 tools/changelog.py 
Traceback (most recent call last):
  File "tools/changelog.py", line 139, in <module>
    sys.exit(main())
  File "tools/changelog.py", line 119, in main
    loglines = create_changelog(json_response)
  File "tools/changelog.py", line 59, in create_changelog
    title = normalize_title(issue['title'])
  File "tools/changelog.py", line 87, in normalize_title
    title = log_line.format(msg=m.groupdict())
AttributeError: 'NoneType' object has no attribute 'groupdict'
```

**Comment by miketaylr** [comment]
Rude 🤖
