### ISSUE TITLE
502 bad gateway for the new form.

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#3061]
@miketaylr 

Deployed version `88e0c6fee6e3dc062fc6ee6c4676980c0e8b27a4`

when requesting `"GET /issues/new HTTP/2.0"`
with the cookie `exp=form-v2`

```
Oct 28 02:26:01 staging-server webcompat-staging: Traceback (most recent call last):
Oct 28 02:26:01 staging-server webcompat-staging:   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2309, in __call__
Oct 28 02:26:01 staging-server webcompat-staging:     return self.wsgi_app(environ, start_response)
Oct 28 02:26:01 staging-server webcompat-staging:   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2295, in wsgi_app
Oct 28 02:26:01 staging-server webcompat-staging:     response = self.handle_exception(e)
Oct 28 02:26:01 staging-server webcompat-staging:   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1741, in handle_exception
Oct 28 02:26:01 staging-server webcompat-staging:     reraise(exc_type, exc_value, tb)
Oct 28 02:26:01 staging-server webcompat-staging:   File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 35, in reraise
Oct 28 02:26:01 staging-server webcompat-staging:     raise value
Oct 28 02:26:01 staging-server webcompat-staging:   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2292, in wsgi_app
Oct 28 02:26:01 staging-server webcompat-staging:     response = self.full_dispatch_request()
Oct 28 02:26:01 staging-server webcompat-staging:   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
Oct 28 02:26:01 staging-server webcompat-staging:     rv = self.handle_user_exception(e)
Oct 28 02:26:01 staging-server webcompat-staging:   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
Oct 28 02:26:01 staging-server webcompat-staging:     reraise(exc_type, exc_value, tb)
Oct 28 02:26:01 staging-server webcompat-staging:   File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 35, in reraise
Oct 28 02:26:01 staging-server webcompat-staging:     raise value
Oct 28 02:26:01 staging-server webcompat-staging:   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
Oct 28 02:26:01 staging-server webcompat-staging:     rv = self.dispatch_request()
Oct 28 02:26:01 staging-server webcompat-staging:   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1799, in dispatch_request
Oct 28 02:26:01 staging-server webcompat-staging:     return self.view_functions[rule.endpoint](**req.view_args)
Oct 28 02:26:01 staging-server webcompat-staging:   File "./webcompat/views.py", line 275, in create_issue
Oct 28 02:26:01 staging-server webcompat-staging:     campaign=campaign, nonce=request.nonce)
Oct 28 02:26:01 staging-server webcompat-staging:   File "/usr/local/lib/python3.7/dist-packages/flask/templating.py", line 135, in render_template
Oct 28 02:26:01 staging-server webcompat-staging:     context, ctx.app)
Oct 28 02:26:01 staging-server webcompat-staging:   File "/usr/local/lib/python3.7/dist-packages/flask/templating.py", line 117, in _render
Oct 28 02:26:01 staging-server webcompat-staging:     rv = template.render(context)
Oct 28 02:26:01 staging-server webcompat-staging:   File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
Oct 28 02:26:01 staging-server webcompat-staging:     return original_render(self, *args, **kwargs)
Oct 28 02:26:01 staging-server webcompat-staging:   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
Oct 28 02:26:01 staging-server webcompat-staging:     return self.environment.handle_exception(exc_info, True)
Oct 28 02:26:01 staging-server webcompat-staging:   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
Oct 28 02:26:01 staging-server webcompat-staging:     reraise(exc_type, exc_value, tb)
Oct 28 02:26:01 staging-server webcompat-staging:   File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
Oct 28 02:26:01 staging-server webcompat-staging:     raise value.with_traceback(tb)
Oct 28 02:26:01 staging-server webcompat-staging:   File "/home/webcompat/staging.webcompat.com/webcompat/templates/new-issue.html", line 1, in top-level template code
Oct 28 02:26:01 staging-server webcompat-staging:     {%- extends "layout.html" -%}
Oct 28 02:26:01 staging-server webcompat-staging:   File "/home/webcompat/staging.webcompat.com/webcompat/templates/layout.html", line 16, in top-level template code
Oct 28 02:26:01 staging-server webcompat-staging:     {% block body %}{% endblock %}
Oct 28 02:26:01 staging-server webcompat-staging:   File "/home/webcompat/staging.webcompat.com/webcompat/templates/new-issue.html", line 18, in block "body"
Oct 28 02:26:01 staging-server webcompat-staging:     {% include "issue-wizard-form.html" %}
Oct 28 02:26:01 staging-server webcompat-staging:   File "/usr/local/lib/python3.7/dist-packages/flask/templating.py", line 58, in get_source
Oct 28 02:26:01 staging-server webcompat-staging:     return self._get_source_fast(environment, template)
Oct 28 02:26:01 staging-server webcompat-staging:   File "/usr/local/lib/python3.7/dist-packages/flask/templating.py", line 86, in _get_source_fast
Oct 28 02:26:01 staging-server webcompat-staging:     raise TemplateNotFound(template)
Oct 28 02:26:01 staging-server webcompat-staging: jinja2.exceptions.TemplateNotFound: issue-wizard-form.html

```

**Comment by karlcow** [comment]
It can be reproduced on localhost with 
`document.cookie = 'exp=form-v2'`
through the console.

**Comment by karlcow** [comment]
The file has been sent to the server.

```
webcompat/templates/contributors/web-platform-research.html
webcompat/templates/home-page/
webcompat/templates/home-page/browse-issues.html
webcompat/templates/home-page/hero.html
webcompat/templates/home-page/how-it-works.html
webcompat/templates/home-page/issue-wizard-form.html
webcompat/templates/home-page/join-us.html
webcompat/templates/issue/
webcompat/templates/issue/aside.jst
webcompat/templates/issue/issue-aside.html
```

@miketaylr And my bad for not catching it when reviewing it.
The templates link has been modified but not the files. 
https://github.com/webcompat/webcompat.com/commit/b82cd01d877b0a8358c7ef959df2aa87ec685afa

Grrmbl to deploy without tests.

**Comment by miketaylr** [comment]
> Grrmbl to deploy without tests.

:(

Sorry for the extra work, @karlcow.
