### ISSUE TITLE
sqlalchemy.orm.exc.DetachedInstanceError error related to ab_exempt

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#3170]
So to reproduce.
With master.
```
flask run
```

1. Go to http://127.0.0.1:5000/
2. Click on login

There's an error message:

```

127.0.0.1 - - [29/Jan/2020 14:28:47] "GET /login HTTP/1.1" 302 -
127.0.0.1 - - [29/Jan/2020 14:28:47] "GET /callback?code=c56637b03a7f44775127 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/karl/code/webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/karl/code/webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/karl/code/webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/karl/code/webcompat.com/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/karl/code/webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/karl/code/webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/karl/code/webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 1969, in finalize_request
    response = self.process_response(response)
  File "/Users/karl/code/webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 2266, in process_response
    response = handler(response)
  File "/Users/karl/code/webcompat.com/webcompat/views.py", line 79, in after_request
    ab_init(response)
  File "/Users/karl/code/webcompat.com/webcompat/helpers.py", line 737, in ab_init
    if ab_exempt():
  File "/Users/karl/code/webcompat.com/webcompat/helpers.py", line 699, in ab_exempt
    if g.user and g.user.user_id in app.config['AB_EXEMPT_USERS']:
  File "/Users/karl/code/webcompat.com/env/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 282, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/Users/karl/code/webcompat.com/env/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 705, in get
    value = state._load_expired(state, passive)
  File "/Users/karl/code/webcompat.com/env/lib/python3.7/site-packages/sqlalchemy/orm/state.py", line 660, in _load_expired
    self.manager.deferred_scalar_loader(self, toload)
  File "/Users/karl/code/webcompat.com/env/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 913, in load_scalar_attributes
    "attribute refresh operation cannot proceed" % (state_str(state))
sqlalchemy.orm.exc.DetachedInstanceError: Instance <User at 0x1046cdf50> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: http://sqlalche.me/e/bhk3)
```

**Comment by miketaylr** [comment]
I'm not able to reproduce, but @magsout was. It seems like it's possible to get in some weird state related to GitHub OAuth.
