### ISSUE TITLE
500 in webhook on staging

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3178]
Trying to sort out STR:

`public_number = get_public_issue_number(issue_info['public_url'])#012KeyError: 'public_url'`

```
Feb  5 17:09:36 staging-server webcompat-staging: [2020-02-05 17:09:36,463] ERROR in app: Exception on /webhooks/labeler [POST]#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2292, in wsgi_app#012    response = self.full_dispatch_request()#012  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request#012    rv = self.handle_user_exception(e)#012  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1718, in handle_user_exception#012    reraise(exc_type, exc_value, tb)#012  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 35, in reraise#012    raise value#012  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request#012    rv = self.dispatch_request()#012  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1799, in dispatch_request#012    return self.view_functions[rule.endpoint](**req.view_args)#012  File "./webcompat/webhooks/__init__.py", line 38, in hooklistener#012    response = process_issue_action(issue_info)#012  File "./webcompat/webhooks/helpers.py", line 278, in process_issue_action#012    response = private_issue_rejected(issue_info)#012  File "./webcompat/webhooks/helpers.py", line 374, in private_issue_rejected#012    public_number = get_public_issue_number(issue_info['public_url'])#012KeyError: 'public_url'
Feb  5 17:09:36 staging-server webcompat-staging: [2020-02-05 17:09:36,464] ERROR in __init__: Exception thrown:#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2292, in wsgi_app#012    response = self.full_dispatch_request()#012  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request#012    rv = self.handle_user_exception(e)#012  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1718, in handle_user_exception#012    reraise(exc_type, exc_value, tb)#012  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 35, in reraise#012    raise value#012  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request#012    rv = self.dispatch_request()#012  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1799, in dispatch_request#012    return self.view_functions[rule.endpoint](**req.view_args)#012  File "./webcompat/webhooks/__init__.py", line 38, in hooklistener#012    response = process_issue_action(issue_info)#012  File "./webcompat/webhooks/helpers.py", line 278, in process_issue_action#012    response = private_issue_rejected(issue_info)#012  File "./webcompat/webhooks/helpers.py", line 374, in private_issue_rejected#012    public_number = get_public_issue_number(issue_info['public_url'])#012KeyError: 'public_url'
```

**Comment by miketaylr** [comment]
It seems like STR is to file a new bug on staging, and from the private repo, close it.

Expected behavior: the rejected moderation queue template updates the public issue, and we don't get a 500 in the webhook response.

**Comment by miketaylr** [comment]
Note to self for testing webhooks locally: https://github.com/miketaylr/web-bugs-issue-tagger#testing-locally

**Comment by miketaylr** [comment]
(ok, if i disable checking signatures locally, because i'm too lazy to figure that out...), this reproduces locally:

```
Traceback (most recent call last):
  File "/Users/miket/dev/webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/miket/dev/webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/miket/dev/webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/miket/dev/webcompat.com/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/miket/dev/webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/miket/dev/webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/miket/dev/webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/miket/dev/webcompat.com/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/miket/dev/webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/miket/dev/webcompat.com/env/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/miket/dev/webcompat.com/webcompat/webhooks/__init__.py", line 38, in hooklistener
    response = process_issue_action(issue_info)
  File "/Users/miket/dev/webcompat.com/webcompat/webhooks/helpers.py", line 278, in process_issue_action
    response = private_issue_rejected(issue_info)
  File "/Users/miket/dev/webcompat.com/webcompat/webhooks/helpers.py", line 374, in private_issue_rejected
    public_number = get_public_issue_number(issue_info['public_url'])
KeyError: 'public_url'
```

**Comment by miketaylr** [comment]
At this point, `issue_info` looks like this:

```
{
   'title':'example.com - site is not usable',
   'state':'closed',
   'action':'closed',
   'number':40,
   'domain':'example.com',
   'repository_url':'https://api.github.com/repos/webcompat/webcompat-tests-private',
   'body':"<!-- @browser: Firefox 73.0 -->\n<!-- @ua_header: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:73.0) Gecko/20100101 Firefox/73.0 -->\n<!-- @reported_with:  -->\n<!-- @public_url: https://github.com/webcompat/webcompat-tests/issues/2361 -->\n<!-- @extra_labels: form-v2-experiment -->\n\n**URL**: http://example.com\n\n**Browser / Version**: Firefox 73.0\n**Operating System**: Mac OS X 10.14\n**Tested Another Browser**: Yes Opera\n\n**Problem type**: Site is not usable\n**Description**: Missing items\n**Steps to Reproduce**:\npublic_number = get_public_issue_number(issue_info['public_url'])#012KeyError: 'public_url'\n\n<details>\n<summary>Browser Configuration</summary>\n<ul>\n  <li>None</li>\n</ul>\n</details>\n\n_From [webcompat.com](https://webcompat.com/) with ❤️_",
   'original_labels':[]
}
```

So yeah, it's missing the `public_url` key.

**Comment by miketaylr** [comment]
The bug is here: https://github.com/webcompat/webcompat.com/blob/d8797bddd462c7690aa45cac38c05f2066c5a6e4/webcompat/webhooks/helpers.py#L165

This assumes the public_url is only relevant for a "milestoned" webhook event action, but for a "closed" action, there is not top-level `milestone` key and we fail to grab the `public_url`.

**Comment by miketaylr** [comment]
@karlcow want to take care of this one?

**Comment by miketaylr** [comment]
I see that private_milestone_closed.json has a top-level `milestone` key, I'm not sure that's accurate. This is the the payload I see from the webhook interface:

[payload.txt](https://github.com/webcompat/webcompat.com/files/4161393/payload.txt)

(there is a milestone *inside* the top-level `issue` key)

**Comment by karlcow** [comment]
houla that payload is… funky.

```
<!-- @browser: Firefox 73.0 -->
<!-- @ua_header: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:73.0) Gecko/20100101 Firefox/73.0 -->
<!-- @reported_with:  -->
<!-- @public_url: https://github.com/webcompat/webcompat-tests/issues/2361 -->
<!-- @extra_labels: form-v2-experiment -->

**URL**: http://example.com

**Browser / Version**: Firefox 73.0
**Operating System**: Mac OS X 10.14
**Tested Another Browser**: Yes Opera

**Problem type**: Site is not usable
**Description**: Missing items
**Steps to Reproduce**:
public_number = get_public_issue_number(issue_info['public_url'])#012KeyError: 'public_url'

<details>
<summary>Browser Configuration</summary>
<ul>
  <li>None</li>
</ul>
</details>

_From [webcompat.com](https://webcompat.com/) with ❤️_
```

So that's another mistake.

**Comment by karlcow** [comment]
Ah no this is mike… pasting garbage text 🤣 
https://github.com/webcompat/webcompat-tests-private/issues/41
