### ISSUE TITLE
Upgrade python dependencies 

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#3187]
werkzeug project has deprecated a couple of things, and this has created regressions for some modules.
https://requires.io/github/webcompat/webcompat.com/requirements/?branch=master

specifically this case.
https://github.com/webcompat/webcompat.com/pull/3185#issuecomment-583313102

**Comment by karlcow** [comment]
```
(env) ~/code/webcompat.com % pip install -r config/requirements-dev.txt 
Requirement already satisfied: blinker==1.4 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 1)) (1.4)
Requirement already satisfied: Flask==1.1.1 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 2)) (1.1.1)
Requirement already satisfied: Flask-Firehose==0.2.2 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 3)) (0.2.2)
Requirement already satisfied: Flask-Limiter==1.0.1 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 4)) (1.0.1)
Requirement already satisfied: Flask-SQLAlchemy==2.4.0 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 5)) (2.4.0)
Requirement already satisfied: Flask-WTF==0.14.2 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 6)) (0.14.2)
Requirement already satisfied: GitHub-Flask==3.2.0 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 7)) (3.2.0)
Collecting Pillow==6.2.0
  Using cached https://files.pythonhosted.org/packages/a4/92/801710e21ede5f583c6bde61b25baa46ed16d9d77d74935e11b9a801cdd7/Pillow-6.2.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Requirement already satisfied: python-dotenv==0.10.3 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 9)) (0.10.3)
Requirement already satisfied: requests==2.22.0 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 10)) (2.22.0)
Requirement already satisfied: ua-parser==0.8 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 11)) (0.8.0)
Requirement already satisfied: WTForms==2.2.1 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 12)) (2.2.1)
Requirement already satisfied: mock==3.0.5 in ./env/lib/python3.7/site-packages (from -r config/requirements-dev.txt (line 3)) (3.0.5)
Requirement already satisfied: nose==1.3.7 in ./env/lib/python3.7/site-packages (from -r config/requirements-dev.txt (line 4)) (1.3.7)
Requirement already satisfied: pycodestyle==2.5.0 in ./env/lib/python3.7/site-packages (from -r config/requirements-dev.txt (line 5)) (2.5.0)
Requirement already satisfied: click>=5.1 in ./env/lib/python3.7/site-packages (from Flask==1.1.1->-r config/requirements.txt (line 2)) (7.0)
Requirement already satisfied: itsdangerous>=0.24 in ./env/lib/python3.7/site-packages (from Flask==1.1.1->-r config/requirements.txt (line 2)) (1.1.0)
Requirement already satisfied: Jinja2>=2.10.1 in ./env/lib/python3.7/site-packages (from Flask==1.1.1->-r config/requirements.txt (line 2)) (2.10.1)
Requirement already satisfied: Werkzeug>=0.15 in ./env/lib/python3.7/site-packages (from Flask==1.1.1->-r config/requirements.txt (line 2)) (0.15.5)
Requirement already satisfied: six>=1.4.1 in ./env/lib/python3.7/site-packages (from Flask-Limiter==1.0.1->-r config/requirements.txt (line 4)) (1.12.0)
Requirement already satisfied: limits in ./env/lib/python3.7/site-packages (from Flask-Limiter==1.0.1->-r config/requirements.txt (line 4)) (1.3)
Requirement already satisfied: SQLAlchemy>=0.8.0 in ./env/lib/python3.7/site-packages (from Flask-SQLAlchemy==2.4.0->-r config/requirements.txt (line 5)) (1.3.7)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./env/lib/python3.7/site-packages (from requests==2.22.0->-r config/requirements.txt (line 10)) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in ./env/lib/python3.7/site-packages (from requests==2.22.0->-r config/requirements.txt (line 10)) (2019.6.16)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./env/lib/python3.7/site-packages (from requests==2.22.0->-r config/requirements.txt (line 10)) (1.25.3)
Requirement already satisfied: idna<2.9,>=2.5 in ./env/lib/python3.7/site-packages (from requests==2.22.0->-r config/requirements.txt (line 10)) (2.8)
Requirement already satisfied: MarkupSafe>=0.23 in ./env/lib/python3.7/site-packages (from Jinja2>=2.10.1->Flask==1.1.1->-r config/requirements.txt (line 2)) (1.1.1)
Installing collected packages: Pillow
  Found existing installation: Pillow 6.1.0
    Uninstalling Pillow-6.1.0:
      Successfully uninstalled Pillow-6.1.0
Successfully installed Pillow-6.2.0
WARNING: You are using pip version 19.3.1; however, version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(env) ~/code/webcompat.com % pip install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/54/0c/d01aa759fdc501a58f431eb594a17495f15b88da142ce14b5845662c13f3/pip-20.0.2-py2.py3-none-any.whl (1.4MB)
     |████████████████████████████████| 1.4MB 626kB/s 
Installing collected packages: pip
  Found existing installation: pip 19.3.1
    Uninstalling pip-19.3.1:
      Successfully uninstalled pip-19.3.1
Successfully installed pip-20.0.2
(env) ~/code/webcompat.com % pip install -r config/requirements-dev.txt
Requirement already satisfied: blinker==1.4 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 1)) (1.4)
Requirement already satisfied: Flask==1.1.1 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 2)) (1.1.1)
Requirement already satisfied: Flask-Firehose==0.2.2 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 3)) (0.2.2)
Requirement already satisfied: Flask-Limiter==1.0.1 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 4)) (1.0.1)
Requirement already satisfied: Flask-SQLAlchemy==2.4.0 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 5)) (2.4.0)
Requirement already satisfied: Flask-WTF==0.14.2 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 6)) (0.14.2)
Requirement already satisfied: GitHub-Flask==3.2.0 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 7)) (3.2.0)
Requirement already satisfied: Pillow==6.2.0 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 8)) (6.2.0)
Requirement already satisfied: python-dotenv==0.10.3 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 9)) (0.10.3)
Requirement already satisfied: requests==2.22.0 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 10)) (2.22.0)
Requirement already satisfied: ua-parser==0.8 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 11)) (0.8.0)
Requirement already satisfied: WTForms==2.2.1 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 12)) (2.2.1)
Requirement already satisfied: mock==3.0.5 in ./env/lib/python3.7/site-packages (from -r config/requirements-dev.txt (line 3)) (3.0.5)
Requirement already satisfied: nose==1.3.7 in ./env/lib/python3.7/site-packages (from -r config/requirements-dev.txt (line 4)) (1.3.7)
Requirement already satisfied: pycodestyle==2.5.0 in ./env/lib/python3.7/site-packages (from -r config/requirements-dev.txt (line 5)) (2.5.0)
Requirement already satisfied: click>=5.1 in ./env/lib/python3.7/site-packages (from Flask==1.1.1->-r config/requirements.txt (line 2)) (7.0)
Requirement already satisfied: Werkzeug>=0.15 in ./env/lib/python3.7/site-packages (from Flask==1.1.1->-r config/requirements.txt (line 2)) (0.15.5)
Requirement already satisfied: itsdangerous>=0.24 in ./env/lib/python3.7/site-packages (from Flask==1.1.1->-r config/requirements.txt (line 2)) (1.1.0)
Requirement already satisfied: Jinja2>=2.10.1 in ./env/lib/python3.7/site-packages (from Flask==1.1.1->-r config/requirements.txt (line 2)) (2.10.1)
Requirement already satisfied: six>=1.4.1 in ./env/lib/python3.7/site-packages (from Flask-Limiter==1.0.1->-r config/requirements.txt (line 4)) (1.12.0)
Requirement already satisfied: limits in ./env/lib/python3.7/site-packages (from Flask-Limiter==1.0.1->-r config/requirements.txt (line 4)) (1.3)
Requirement already satisfied: SQLAlchemy>=0.8.0 in ./env/lib/python3.7/site-packages (from Flask-SQLAlchemy==2.4.0->-r config/requirements.txt (line 5)) (1.3.7)
Requirement already satisfied: certifi>=2017.4.17 in ./env/lib/python3.7/site-packages (from requests==2.22.0->-r config/requirements.txt (line 10)) (2019.6.16)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./env/lib/python3.7/site-packages (from requests==2.22.0->-r config/requirements.txt (line 10)) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in ./env/lib/python3.7/site-packages (from requests==2.22.0->-r config/requirements.txt (line 10)) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./env/lib/python3.7/site-packages (from requests==2.22.0->-r config/requirements.txt (line 10)) (1.25.3)
Requirement already satisfied: MarkupSafe>=0.23 in ./env/lib/python3.7/site-packages (from Jinja2>=2.10.1->Flask==1.1.1->-r config/requirements.txt (line 2)) (1.1.1)
```

Let's uninstall werkzeug,

```
(env) ~/code/webcompat.com % pip uninstall Werkzeug                    
Found existing installation: Werkzeug 0.15.5
Uninstalling Werkzeug-0.15.5:
  Would remove:
    /Users/karl/code/webcompat.com/env/lib/python3.7/site-packages/Werkzeug-0.15.5.dist-info/*
    /Users/karl/code/webcompat.com/env/lib/python3.7/site-packages/werkzeug/*
Proceed (y/n)? y   
  Successfully uninstalled Werkzeug-0.15.5
```

then reinstall the project.

```
(env) ~/code/webcompat.com % pip install -r config/requirements-dev.txt
Requirement already satisfied: blinker==1.4 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 1)) (1.4)
Requirement already satisfied: Flask==1.1.1 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 2)) (1.1.1)
Requirement already satisfied: Flask-Firehose==0.2.2 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 3)) (0.2.2)
Requirement already satisfied: Flask-Limiter==1.0.1 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 4)) (1.0.1)
Requirement already satisfied: Flask-SQLAlchemy==2.4.0 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 5)) (2.4.0)
Requirement already satisfied: Flask-WTF==0.14.2 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 6)) (0.14.2)
Requirement already satisfied: GitHub-Flask==3.2.0 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 7)) (3.2.0)
Requirement already satisfied: Pillow==6.2.0 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 8)) (6.2.0)
Requirement already satisfied: python-dotenv==0.10.3 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 9)) (0.10.3)
Requirement already satisfied: requests==2.22.0 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 10)) (2.22.0)
Requirement already satisfied: ua-parser==0.8 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 11)) (0.8.0)
Requirement already satisfied: WTForms==2.2.1 in ./env/lib/python3.7/site-packages (from -r config/requirements.txt (line 12)) (2.2.1)
Requirement already satisfied: mock==3.0.5 in ./env/lib/python3.7/site-packages (from -r config/requirements-dev.txt (line 3)) (3.0.5)
Requirement already satisfied: nose==1.3.7 in ./env/lib/python3.7/site-packages (from -r config/requirements-dev.txt (line 4)) (1.3.7)
Requirement already satisfied: pycodestyle==2.5.0 in ./env/lib/python3.7/site-packages (from -r config/requirements-dev.txt (line 5)) (2.5.0)
Requirement already satisfied: itsdangerous>=0.24 in ./env/lib/python3.7/site-packages (from Flask==1.1.1->-r config/requirements.txt (line 2)) (1.1.0)
Requirement already satisfied: Jinja2>=2.10.1 in ./env/lib/python3.7/site-packages (from Flask==1.1.1->-r config/requirements.txt (line 2)) (2.10.1)
Requirement already satisfied: click>=5.1 in ./env/lib/python3.7/site-packages (from Flask==1.1.1->-r config/requirements.txt (line 2)) (7.0)
Collecting Werkzeug>=0.15
  Downloading Werkzeug-1.0.0-py2.py3-none-any.whl (298 kB)
     |████████████████████████████████| 298 kB 1.3 MB/s 
Requirement already satisfied: limits in ./env/lib/python3.7/site-packages (from Flask-Limiter==1.0.1->-r config/requirements.txt (line 4)) (1.3)
Requirement already satisfied: six>=1.4.1 in ./env/lib/python3.7/site-packages (from Flask-Limiter==1.0.1->-r config/requirements.txt (line 4)) (1.12.0)
Requirement already satisfied: SQLAlchemy>=0.8.0 in ./env/lib/python3.7/site-packages (from Flask-SQLAlchemy==2.4.0->-r config/requirements.txt (line 5)) (1.3.7)
Requirement already satisfied: idna<2.9,>=2.5 in ./env/lib/python3.7/site-packages (from requests==2.22.0->-r config/requirements.txt (line 10)) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./env/lib/python3.7/site-packages (from requests==2.22.0->-r config/requirements.txt (line 10)) (1.25.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./env/lib/python3.7/site-packages (from requests==2.22.0->-r config/requirements.txt (line 10)) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in ./env/lib/python3.7/site-packages (from requests==2.22.0->-r config/requirements.txt (line 10)) (2019.6.16)
Requirement already satisfied: MarkupSafe>=0.23 in ./env/lib/python3.7/site-packages (from Jinja2>=2.10.1->Flask==1.1.1->-r config/requirements.txt (line 2)) (1.1.1)
Installing collected packages: Werkzeug
Successfully installed Werkzeug-1.0.0
```


ok.
Let's try the tests.

```
% nosetests
EEEEEEEEEE..EEEE
…


======================================================================
ERROR: Failure: ImportError (cannot import name 'url_encode' from 'werkzeug' (/Users/karl/code/webcompat.com/env/lib/python3.7/site-packages/werkzeug/__init__.py))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/karl/code/webcompat.com/env/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/karl/code/webcompat.com/env/lib/python3.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/karl/code/webcompat.com/env/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/karl/code/webcompat.com/env/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/karl/code/webcompat.com/tests/unit/test_webhook.py", line 17, in <module>
    import webcompat
  File "/Users/karl/code/webcompat.com/webcompat/__init__.py", line 35, in <module>
    import webcompat.views  # noqa
  File "/Users/karl/code/webcompat.com/webcompat/views.py", line 23, in <module>
    from webcompat.form import AUTH_REPORT
  File "/Users/karl/code/webcompat.com/webcompat/form.py", line 20, in <module>
    from flask_wtf import FlaskForm
  File "/Users/karl/code/webcompat.com/env/lib/python3.7/site-packages/flask_wtf/__init__.py", line 17, in <module>
    from .recaptcha import *
  File "/Users/karl/code/webcompat.com/env/lib/python3.7/site-packages/flask_wtf/recaptcha/__init__.py", line 2, in <module>
    from .fields import *
  File "/Users/karl/code/webcompat.com/env/lib/python3.7/site-packages/flask_wtf/recaptcha/fields.py", line 3, in <module>
    from . import widgets
  File "/Users/karl/code/webcompat.com/env/lib/python3.7/site-packages/flask_wtf/recaptcha/widgets.py", line 5, in <module>
    from werkzeug import url_encode
ImportError: cannot import name 'url_encode' from 'werkzeug' (/Users/karl/code/webcompat.com/env/lib/python3.7/site-packages/werkzeug/__init__.py)

----------------------------------------------------------------------
Ran 16 tests in 0.749s

FAILED (errors=14)
```

💥 💣 

so that's what is happening on CircleCI.

**Comment by karlcow** [comment]
```
diff --git a/config/requirements.txt b/config/requirements.txt
index 13e46099..ac3d3c52 100644
--- a/config/requirements.txt
+++ b/config/requirements.txt
@@ -3,7 +3,7 @@ Flask==1.1.1
 Flask-Firehose==0.2.2
 Flask-Limiter==1.0.1
 Flask-SQLAlchemy==2.4.0
-Flask-WTF==0.14.2
+Flask-WTF==0.14.3
 GitHub-Flask==3.2.0
 Pillow==6.2.0
 python-dotenv==0.10.3
```

then 

```
Installing collected packages: Flask-WTF
  Attempting uninstall: Flask-WTF
    Found existing installation: Flask-WTF 0.14.2
    Uninstalling Flask-WTF-0.14.2:
      Successfully uninstalled Flask-WTF-0.14.2
Successfully installed Flask-WTF-0.14.3
```

nosetests still failing, but different errors, 2 types

```
  File "/Users/karl/code/webcompat.com/tests/unit/test_uploads.py", line 17, in <module>
    from werkzeug import FileStorage
ImportError: cannot import name 'FileStorage' from 'werkzeug' (/Users/karl/code/webcompat.com/env/lib/python3.7/site-packages/werkzeug/__init__.py)
```

```
  File "/Users/karl/code/webcompat.com/tests/unit/test_issues.py", line 16, in <module>
    from werkzeug import MultiDict
ImportError: cannot import name 'MultiDict' from 'werkzeug' (/Users/karl/code/webcompat.com/env/lib/python3.7/site-packages/werkzeug/__init__.py)
```

These will need to fix in our code. :)

**Comment by miketaylr** [comment]
> +Flask-WTF==0.14.3

...which was released yesterday. wow.
