### ISSUE TITLE
Investigate (and fix!) flaky test

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#3476]
Since I landed this test, I've seen it fail a couple of times. Usually re-triggering the tests is sufficient to get it to pass.

```
× firefox on linux 4.15.0-1077-aws - Reporting with wizard - Learn more modal - closing with Esc (10.302s)
    NoSuchElement: An element could not be located on the page using the given search parameters.
      at runMicrotasks @ anonymous
      at Test.Learn more modal - closing with Esc [as test] @ tests/functional/reporting-issue-wizard-non-auth.js:646:12
      @ src/lib/Test.ts:268:51
      at runMicrotasks @ anonymous
```

**Comment by miketaylr** [comment]
![Screen Shot 2020-09-02 at 3 07 12 PM](https://user-images.githubusercontent.com/67283/92031297-0405f800-ed2e-11ea-8229-ecad362f281b.png)

**Comment by miketaylr** [comment]
```
× chrome 85.0.4183.121 on Linux - Reporting with wizard - Wizard stepper - scenario 1 (5.969s)
    AssertionError: expected 'Screenshot' to include 'Send report'
      at Command.<anonymous> @ tests/functional/reporting-issue-wizard-non-auth.js:218:20
      at Test.Wizard stepper - scenario 1 [as test] @ tests/functional/reporting-issue-wizard-non-auth.js:216:12
      @ src/lib/Test.ts:268:51
      at runMicrotasks @ anonymous
```
