### ISSUE TITLE
[http] JSON errors for APIs communications

### ISSUE THREAD

**Issue by karlcow** [webcompat/webcompat.com#667]
Tested locally.

```
→ http GET http://localhost:5000/api/issues/100/labels 'Accept: application/json'
```

When doing this call, we receive in return a `404 Not Found`, which is fine except for the body which is a full HTML file. Unnecessary bytes on the wire.

We might want to send either nothing in the body `Content-Length: 0` or a very simple JSON body explaining the error.

**Comment by karlcow** [comment]
All the routes not checked should be fixed. All of them tested with  the pattern

`http  GET http://localhost:5000/api/somePath 'Accept: application/json'`


* [x] `/api/issues/57000` 404 not found. JSON. OK!
* [ ] `/api/bar/` 404 not found. HTML. TOFIX
* [ ] `/api/issues/category/mine` 302 found. redirect to homepage. (not authenticated) TOFIX
* [ ] `/api/issues/category/foobar` 404 Not found. HTML. TOFIX
* [ ] `/api/issues/search?z=foobar` 500 Internal server error. HTML. TOFIX
* [ ] `/api/issues/search/foobar` 500 Internal server error. HTML. TOFIX
* [x] `/api/issues/10000000/comments` 404 not found. json. OK!
* [ ] `/api/issues/labels` 401 Unauthorized. HTML. TOFIX

**Comment by karlcow** [comment]
To keep this around for memory, maybe simpler.
http://www.flaskapi.org/api-guide/exceptions/

**Comment by karlcow** [comment]
Just realized also that we app.errorhandler in views.py

https://github.com/webcompat/webcompat.com/blob/master/webcompat/views.py#L226-L265

The one I added for JSON was in 
https://github.com/webcompat/webcompat.com/blob/master/webcompat/helpers.py#L304

Maybe I should straighten this a  bit, and I wonder if I can be more clever in terms of observing the Accept header into errorhandler and send the appropriate answer depending on the mime type.

**Comment by karlcow** [comment]
This could be another way of handling it And it would avoid to manage it at different places. 


```
@app.errorhandler(404)
def page_not_found(e):
    if request.accept_mimetypes.accept_json and \
            not request.accept_mimetypes.accept_html:
        response = jsonify({'error': 'not found'})
        response.status_code = 404
        return response
    return render_template('404.html'), 404
```

**Comment by karlcow** [comment]
OK my previous comment seems to be what has to be done. I tested on the CLI and it's working as expected. Now I have to figure out how to configure `app.get` so it sends `Accept: application/json`.

**Comment by karlcow** [comment]
OK found!  I just needed to do

```python
headers = {'HTTP_USER_AGENT': ('Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; '
                               'rv:31.0) Gecko/20100101 Firefox/31.0'),
           'HTTP_ACCEPT': 'application/json'}
```

**Comment by karlcow** [comment]
Let's fix this with a 404.

```
127.0.0.1 - - [18/Aug/2015 15:06:18] "GET /api/issues/search?z=foobar HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages/flask_limiter/extension.py", line 285, in __inner
    return obj(*a, **k)
  File "/Users/karl/code/webcompat.com/webcompat/api/endpoints.py", line 182, in get_search_results
    query_string += " repo:{0}".format(REPO_PATH)
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
```

**Comment by karlcow** [comment]
pfew and this is done!

```
→ nosetests -v
API access category/mine without auth returns JSON 401. ... ok
API issue for a non existent number returns JSON 404. ... ok
API issue search with bad keywords returns JSON 404. ... ok
API access to labels without auth returns JSON 401. ... ok
API with wrong parameter returns JSON 404. ... ok
API with wrong category returns JSON 404. ... ok
API with wrong route returns JSON 404. ... ok
Test HTTP Links formating. ... ok
Test that API params are correctly converted to Search API. ... ok
normalize_api_params shouldn't transform unknown params. ... ok
Test HTTP Links parsing for GitHub only. ... ok
test_rewrite_and_sanitize_link (tests.test_helpers.TestHelpers) ... ok
Test we're correctly rewriting the passed in link. ... ok
Test that we're removing access_token parameters. ... ok
Test that /about exists. ... ok
Test that the home page exists. ... ok
Test issues and integer for: ... ok
Test that the /issues/<number> exists, and does not redirect. ... ok
Test that the /issues route gets 200 and does not redirect. ... ok
Test that the new filtering is correct. ... ok
Test that the /login route 302s to GitHub. ... ok
Test that /privacy exists. ... ok
Test that /thanks/1 exists. ... ok

----------------------------------------------------------------------
Ran 23 tests in 7.063s

OK
```

Added 7 tests for the API part.  Hopefully I didn't break anything else. If I did. We are good for more tests. \o/.

Creating the Pull Request.

**Comment by miketaylr** [comment]
Very cool Karl. :)

**Comment by miketaylr** [comment]
:heart:
