### ISSUE TITLE
Intermittent Search test failures

### ISSUE THREAD

**Issue by miketaylr** [webcompat/webcompat.com#890]
This fails pretty frequently, but not 100% of the time. And if you re-trigger a build on Travis it will usually pass after the failure.

So... it would be good to figure out why this happens (and why it's a recent thing).

```
FAIL: main - Search (non-auth) - Search works (3496ms)

AssertionError: The search results show up on the page.: expected 'Issue 280: w3.org - desktop site instead of mobile site' to include 'vladvlad'

  at Function.assert.include  <node_modules/intern/node_modules/chai/chai.js:2977:45>

  at CompatCommand.<anonymous>  <tests/functional/search-non-auth.js:92:18>

  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:509:31>

  at CompatCommand.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:526:11>

  at <node_modules/intern/node_modules/leadfoot/node_modules/dojo/Promise.js:235:37>

  at runCallbacks  <node_modules/intern/node_modules/leadfoot/node_modules/dojo/Promise.js:11:18>

  at <node_modules/intern/node_modules/leadfoot/node_modules/dojo/Promise.js:188:17>

  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/leadfoot/node_modules/dojo/Promise.js:131:29>

  at processImmediate [as _immediateCallback]  <timers.js:354:15>

  at new CompatCommand  <node_modules/intern/runner.js:213:14>

  at CompatCommand.Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:525:10>

  at Test.registerSuite.Search works [as test]  <tests/functional/search-non-auth.js:91:10>

  at Test.run  <node_modules/intern/lib/Test.js:169:19>

  at <node_modules/intern/lib/Suite.js:237:13>

  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>

  at Promise.then.promise.then  <node_modules/intern/node_modules/dojo/Deferred.js:258:5>

  at runTest  <node_modules/intern/lib/Suite.js:236:46>

  at <node_modules/intern/lib/Suite.js:249:7>

  at process._tickCallback  <node.js:442:13>

  at new CompatCommand  <node_modules/intern/runner.js:213:14>

  at CompatCommand.Command.end  <node_modules/intern/node_modules/leadfoot/Command.js:475:10>

  at Test.registerSuite.Search works [as test]  <tests/functional/search-non-auth.js:94:10>

  at Test.run  <node_modules/intern/lib/Test.js:169:19>

  at <node_modules/intern/lib/Suite.js:237:13>

  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>

  at Promise.then.promise.then  <node_modules/intern/node_modules/dojo/Deferred.js:258:5>

  at runTest  <node_modules/intern/lib/Suite.js:236:46>

  at <node_modules/intern/lib/Suite.js:249:7>

  at process._tickCallback  <node.js:442:13>

127.0.0.1 - - [30/Dec/2015 02:19:03] "GET / HTTP/1.1" 200 -

Expected fixture file: /home/travis/build/webcompat/webcompat.com/tests/fixtures/api/issues/labels.6665c4820456e6a813dcbbdddd690ffc.json

127.0.0.1 - - [30/Dec/2015 02:19:03] "GET /api/issues/labels?per_page=100 HTTP/1.1" 200 -

127.0.0.1 - - [30/Dec/2015 02:19:03] "GET /api/issues/category/new HTTP/1.1" 200 -

127.0.0.1 - - [30/Dec/2015 02:19:04] "GET /issues?q=vladvlad HTTP/1.1" 200 -

Expected fixture file: /home/travis/build/webcompat/webcompat.com/tests/fixtures/api/issues/labels.6665c4820456e6a813dcbbdddd690ffc.json

127.0.0.1 - - [30/Dec/2015 02:19:04] "GET /api/issues/labels?per_page=100 HTTP/1.1" 200 -

FAIL: main - Search (non-auth) - Search from the homepage (14080ms)

NoSuchElement: [POST http://localhost:4444/wd/hub/session/a82eeaae-3abd-4880-a73f-bab8a12c0b58/element / {"using":"css selector","value":".wc-IssueItem:nth-of-type(1) a"}] Unable to locate element: {"method":"css selector","selector":".wc-IssueItem:nth-of-type(1) a"}

For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html

Build info: version: '2.48.0', revision: 'b7b081a', time: '2015-10-07 15:48:56'

System info: host: 'testing-worker-linux-docker-8399f37a-3194-linux-5', ip: '172.17.1.255', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-40-generic', java.version: '1.7.0_76'

Driver info: driver.version: unknown

  at Server._post  <node_modules/intern/node_modules/leadfoot/Server.js:68:9>

  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:57:30>

  at ProxiedSession.Session.find  <node_modules/intern/node_modules/leadfoot/Session.js:1053:15>

  at CompatCommand.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:41:36>

  at <node_modules/intern/node_modules/leadfoot/node_modules/dojo/Promise.js:235:37>

  at runCallbacks  <node_modules/intern/node_modules/leadfoot/node_modules/dojo/Promise.js:11:18>

  at <node_modules/intern/node_modules/leadfoot/node_modules/dojo/Promise.js:188:17>

  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/leadfoot/node_modules/dojo/Promise.js:131:29>

  at processImmediate [as _immediateCallback]  <timers.js:354:15>

  at new CompatCommand  <node_modules/intern/runner.js:213:14>

  at CompatCommand.find  <node_modules/intern/node_modules/leadfoot/Command.js:22:10>

  at <CompatCommand.prototype.(anonymous function) [as findByCssSelector] (/home/travis/build/webcompat/webcompat.com/node_modules/intern/node_modules/leadfoot/lib/strategies.js:24:16)>

  at Test.registerSuite.Search from the homepage [as test]  <tests/functional/search-non-auth.js:108:10>

  at Test.run  <node_modules/intern/lib/Test.js:169:19>

  at <node_modules/intern/lib/Suite.js:237:13>

  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>

  at Promise.then.promise.then  <node_modules/intern/node_modules/dojo/Deferred.js:258:5>

  at runTest  <node_modules/intern/lib/Suite.js:236:46>

  at <node_modules/intern/lib/Suite.js:249:7>

  at new CompatCommand  <node_modules/intern/runner.js:213:14>

  at <CompatCommand.target.(anonymous function) [as getVisibleText] (/home/travis/build/webcompat/webcompat.com/node_modules/intern/node_modules/leadfoot/Command.js:656:11)>

  at Test.registerSuite.Search from the homepage [as test]  <tests/functional/search-non-auth.js:108:62>

  at Test.run  <node_modules/intern/lib/Test.js:169:19>

  at <node_modules/intern/lib/Suite.js:237:13>

  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>

  at Promise.then.promise.then  <node_modules/intern/node_modules/dojo/Deferred.js:258:5>

  at runTest  <node_modules/intern/lib/Suite.js:236:46>

  at <node_modules/intern/lib/Suite.js:249:7>

  at process._tickCallback  <node.js:442:13>

  at new CompatCommand  <node_modules/intern/runner.js:213:14>

  at CompatCommand.Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:525:10>

  at Test.registerSuite.Search from the homepage [as test]  <tests/functional/search-non-auth.js:109:10>

  at Test.run  <node_modules/intern/lib/Test.js:169:19>

  at <node_modules/intern/lib/Suite.js:237:13>

  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>

  at Promise.then.promise.then  <node_modules/intern/node_modules/dojo/Deferred.js:258:5>

  at runTest  <node_modules/intern/lib/Suite.js:236:46>

  at <node_modules/intern/lib/Suite.js:249:7>

  at process._tickCallback  <node.js:442:13>

  at new CompatCommand  <node_modules/intern/runner.js:213:14>

  at CompatCommand.Command.end  <node_modules/intern/node_modules/leadfoot/Command.js:475:10>

  at Test.registerSuite.Search from the homepage [as test]  <tests/functional/search-non-auth.js:112:10>

  at Test.run  <node_modules/intern/lib/Test.js:169:19>

  at <node_modules/intern/lib/Suite.js:237:13>

  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>

  at Promise.then.promise.then  <node_modules/intern/node_modules/dojo/Deferred.js:258:5>

  at runTest  <node_modules/intern/lib/Suite.js:236:46>

  at <node_modules/intern/lib/Suite.js:249:7>

  at process._tickCallback  <node.js:442:13>

  at new CompatCommand  <node_modules/intern/runner.js:213:14>

  at <CompatCommand.target.(anonymous function) [as getCurrentUrl] (/home/travis/build/webcompat/webcompat.com/node_modules/intern/node_modules/leadfoot/Command.js:592:11)>

  at Test.registerSuite.Search from the homepage [as test]  <tests/functional/search-non-auth.js:113:10>

  at Test.run  <node_modules/intern/lib/Test.js:169:19>

  at <node_modules/intern/lib/Suite.js:237:13>

  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>

  at Promise.then.promise.then  <node_modules/intern/node_modules/dojo/Deferred.js:258:5>

  at runTest  <node_modules/intern/lib/Suite.js:236:46>

  at <node_modules/intern/lib/Suite.js:249:7>

  at process._tickCallback  <node.js:442:13>

  at new CompatCommand  <node_modules/intern/runner.js:213:14>

  at CompatCommand.Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:525:10>

  at Test.registerSuite.Search from the homepage [as test]  <tests/functional/search-non-auth.js:114:10>

  at Test.run  <node_modules/intern/lib/Test.js:169:19>

  at <node_modules/intern/lib/Suite.js:237:13>

  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>

  at Promise.then.promise.then  <node_modules/intern/node_modules/dojo/Deferred.js:258:5>

  at runTest  <node_modules/intern/lib/Suite.js:236:46>

  at <node_modules/intern/lib/Suite.js:249:7>

  at process._tickCallback  <node.js:442:13>

  at new CompatCommand  <node_modules/intern/runner.js:213:14>

  at CompatCommand.Command.end  <node_modules/intern/node_modules/leadfoot/Command.js:475:10>

  at Test.registerSuite.Search from the homepage [as test]  <tests/functional/search-non-auth.js:117:10>

  at Test.run  <node_modules/intern/lib/Test.js:169:19>

  at <node_modules/intern/lib/Suite.js:237:13>

  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>

  at Promise.then.promise.then  <node_modules/intern/node_modules/dojo/Deferred.js:258:5>

  at runTest  <node_modules/intern/lib/Suite.js:236:46>

  at <node_modules/intern/lib/Suite.js:249:7>

  at process._tickCallback  <node.js:442:13>

2/6 tests failed
```

**Comment by miketaylr** [comment]
These actually went away. Possibly something fixed by GitHub.

**Comment by miketaylr** [comment]
Aw dang, got another one today at https://travis-ci.org/webcompat/webcompat.com/builds/113189652.

(I restarted the test, so that might show green when clicking it).

**Comment by karlcow** [comment]
So the "search works" failing up there is about 

https://github.com/webcompat/webcompat.com/blob/master/tests/functional/search-non-auth.js#L79

The request is 

```HTTP
GET /api/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=vladvlad HTTP/1.1
Host: webcompat.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:46.0) Gecko/20100101 Firefox/46.0
Accept: application/json
Accept-Language: en,fr;q=0.7,en-US;q=0.3
Accept-Encoding: gzip, deflate, br
DNT: 1
Referer: https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=vladvlad
X-Requested-With: XMLHttpRequest
Cookie: session=.…………
Connection: keep-alive
If-None-Match: None
Cache-Control: max-age=0
```

The response is:

``` json 
{
  "total_count": 0,
  "incomplete_results": false,
  "items": [

  ]
}
```

Let's see where it fails.
https://github.com/webcompat/webcompat-tests/issues?q=vladvlad+is%3Aopen+sort%3Acreated-desc

The search returns a valid result on github.

testing on localhost

```
127.0.0.1 - - [03/Mar/2016 10:10:25] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [03/Mar/2016 10:10:28] "GET /api/issues/labels?per_page=100 HTTP/1.1" 304 -
127.0.0.1 - - [03/Mar/2016 10:10:29] "GET /api/issues/category/new HTTP/1.1" 200 -
127.0.0.1 - - [03/Mar/2016 10:10:56] "GET /issues?q=vladvlad HTTP/1.1" 200 -
127.0.0.1 - - [03/Mar/2016 10:10:56] "GET /js/lib/mixins/pagination.js HTTP/1.1" 200 -
127.0.0.1 - - [03/Mar/2016 10:10:56] "GET /js/lib/issue-list.js HTTP/1.1" 200 -
```

I get a flash message telling me something went wrong.

So we need to see what is sent to github and what is received from github.

**Comment by miketaylr** [comment]
The bizarre thing is I've never had this failure locally. And it only fails *sometimes* on Travis.

**Comment by karlcow** [comment]
The failure is happening locally for me. :) There is a route in the api/endpoint for search but it doesn't work for non-auth, I thought we had remove the fact that non-auth users could not search.

`→ http HEAD http://localhost:5000/api/issues/100`

```http
HTTP/1.0 200 OK
Content-Length: 2724
Date: Thu, 03 Mar 2016 01:28:37 GMT
Server: Werkzeug/0.10.4 Python/2.7.10
cache-control: private, max-age=60, s-maxage=60
content-type: application/json
etag: W/"958cdd90b618e2216ffd852712132318"
```


`→ http HEAD http://localhost:5000/api/issues?q=vladvlad`

```http
HTTP/1.0 404 NOT FOUND
Content-Length: 5784
Content-Type: text/html; charset=utf-8
Date: Thu, 03 Mar 2016 01:29:07 GMT
Server: Werkzeug/0.10.4 Python/2.7.10
```

**Comment by karlcow** [comment]
OK after a few breakpoints. Not that above I'm reaching this part 
https://github.com/webcompat/webcompat.com/blob/master/webcompat/api/endpoints.py#L70

we should not happen if we are handling the thing through JS aka
https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/issue-list.js#L311

So I guess we have a first issue here.

I put a breakpoint at
https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/issue-list.js#L338

it goes into the model for issues with normalizeAPIParams

Then it builds the URL
"https://api.github.com/search/issues?page=1&per_page=50&stage=all&sort=created&q=vladvlad+state%3Aopen+repo%3Awebcompat%2Fwebcompat-tests&order=desc"

This URL returns MANUALLY

```json
{
    "incomplete_results": false, 
    "items": [
        {
            "assignee": null, 
            "body": "<!-- @browser: Chrome 35.0.1916 -->\r\n\r\n**URL**: test.com\r\n**Browser / Version**: Chrome 35.0.1916\r\n**Operating System**: Mac OS X 10.9.2\r\n**Problem type**: Unknown\r\n**Site owner**: Unknown\r\n\r\n**Steps to Reproduce**\r\n1) Navigate to: test.com\r\n2) …\r\n\r\nExpected Behavior:\r\nActual Behavior:\r\n\r\n```css\r\nfloat: left\r\n```\r\n", 
            "closed_at": null, 
            "comments": 9, 
            "comments_url": "https://api.github.com/repos/webcompat/webcompat-tests/issues/114/comments", 
            "created_at": "2014-07-15T22:14:21Z", 
            "events_url": "https://api.github.com/repos/webcompat/webcompat-tests/issues/114/events", 
            "html_url": "https://github.com/webcompat/webcompat-tests/issues/114", 
            "id": 37931436, 
            "labels": [
                {
                    "color": "cccccc", 
                    "name": "closed-duplicate", 
                    "url": "https://api.github.com/repos/webcompat/webcompat-tests/labels/closed-duplicate"
                }
            ], 
            "labels_url": "https://api.github.com/repos/webcompat/webcompat-tests/issues/114/labels{/name}", 
            "locked": true, 
            "milestone": null, 
            "number": 114, 
            "repository_url": "https://api.github.com/repos/webcompat/webcompat-tests", 
            "score": 32.340237, 
            "state": "open", 
            "title": "vladvlad", 
            "updated_at": "2014-07-21T14:56:05Z", 
            "url": "https://api.github.com/repos/webcompat/webcompat-tests/issues/114", 
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/8173975?v=3", 
                "events_url": "https://api.github.com/users/testerbuddy2/events{/privacy}", 
                "followers_url": "https://api.github.com/users/testerbuddy2/followers", 
                "following_url": "https://api.github.com/users/testerbuddy2/following{/other_user}", 
                "gists_url": "https://api.github.com/users/testerbuddy2/gists{/gist_id}", 
                "gravatar_id": "", 
                "html_url": "https://github.com/testerbuddy2", 
                "id": 8173975, 
                "login": "testerbuddy2", 
                "organizations_url": "https://api.github.com/users/testerbuddy2/orgs", 
                "received_events_url": "https://api.github.com/users/testerbuddy2/received_events", 
                "repos_url": "https://api.github.com/users/testerbuddy2/repos", 
                "site_admin": false, 
                "starred_url": "https://api.github.com/users/testerbuddy2/starred{/owner}{/repo}", 
                "subscriptions_url": "https://api.github.com/users/testerbuddy2/subscriptions", 
                "type": "User", 
                "url": "https://api.github.com/users/testerbuddy2"
            }
        }
    ], 
    "total_count": 1
}
```

So this part is working. Let's continue with the JS

then this.fetchAndRenderIssues({url: gitHubSearchURL});

the requested url is 
`"https://api.github.com/search/issues?page=1&per_page=50&stage=all&sort=created&q=vladvlad+state%3Aopen+repo%3Awebcompat%2Fwebcompat-tests&order=desc"`

So when it reaches line 361 
https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/issue-list.js#L361

```js
        if (e.responseJSON) {
```

And I'm looking at the Object e in developer tools.

`e.responseJSON` doesn't exist. There is an empty `e.responseText` and readyState is 0

so something happened before hand? Wrong promise or something

Ah… it never goes through the line 355 to 357 in 

```js
      this.issues.fetch(headers).success(_.bind(function() {
        this._loadingIndicator.removeClass('is-active');
        this.render(this.issues);
        issuesPagination.initPaginationLinks(this.issues);
      }
```

**Comment by karlcow** [comment]
Also why do we `fetch` headers instead of a URL? in  `this.issues.fetch(headers)` Or maybe I don't understand how this was supposed to work. 

https://developer.mozilla.org/en-US/docs/Web/API/GlobalFetch
But this seems to say a URI.

**Comment by miketaylr** [comment]
That `fetch` is not the `fetch` you are looking for. :)

(It's http://backbonejs.org/#Model-fetch)

**Comment by karlcow** [comment]
AH! So it nevers goes into success mode.

> Triggers a "change" event if the server's state differs from the current attributes. fetch accepts success and error callbacks in the options hash, which are both passed (model, response, options) as arguments.

**Comment by miketaylr** [comment]
@karlcow can you past the entire `e` object here?

**Comment by karlcow** [comment]
Let's see if it's copy-able in devtools.

`JSON.stringify(e)` in the console:
"{"readyState":0,"responseText":"","status":0,"statusText":"error"}"

and the capture of what the devtools are showing. 

![capture d ecran 2016-03-03 a 13 44 16](https://cloud.githubusercontent.com/assets/505230/13484957/1d523880-e146-11e5-8203-c6f0824dc578.png)

**Comment by karlcow** [comment]
Oh and today I learn about `toSource()` in Firefox.

```
e.toSource()
``` 
gives

```js
({
    readyState: 0,
    getResponseHeader: (function(a) {
        var b;
        if (2 === t) {
            if (!j) {
                j = {};
                while (b = Cc.exec(f)) j[b[1].toLowerCase()] = b[2]
            }
            b = j[a.toLowerCase()]
        }
        return null == b ? null : b
    }),
    getAllResponseHeaders: (function() {
        return 2 === t ? f : null
    }),
    setRequestHeader: (function(a, b) {
        var c = a.toLowerCase();
        return t || (a = s[c] = s[c] || a, r[a] = b), this
    }),
    overrideMimeType: (function(a) {
        return t || (k.mimeType = a), this
    }),
    statusCode: (function(a) {
        var b;
        if (a)
            if (2 > t)
                for (b in a) q[b] = [q[b], a[b]];
            else v.always(a[v.status]);
        return this
    }),
    abort: (function(a) {
        var b = a || u;
        return i && i.abort(b), x(0, b), this
    }),
    state: (function() {
        return c
    }),
    always: (function() {
        return e.done(arguments).fail(arguments), this
    }),
    then: (function() {
        var a = arguments;
        return m.Deferred(function(c) {
            m.each(b, function(b, f) {
                var g = m.isFunction(a[b]) && a[b];
                e[f[1]](function() {
                    var a = g && g.apply(this, arguments);
                    a && m.isFunction(a.promise) ? a.promise().done(c.resolve).fail(c.reject).progress(c.notify) : c[f[0] + "With"](this === d ? c.promise() : this, g ? [a] : arguments)
                })
            }), a = null
        }).promise()
    }),
    promise: (function(a) {
        return null != a ? m.extend(a, d) : d
    }),
    pipe: (function() {
        var a = arguments;
        return m.Deferred(function(c) {
            m.each(b, function(b, f) {
                var g = m.isFunction(a[b]) && a[b];
                e[f[1]](function() {
                    var a = g && g.apply(this, arguments);
                    a && m.isFunction(a.promise) ? a.promise().done(c.resolve).fail(c.reject).progress(c.notify) : c[f[0] + "With"](this === d ? c.promise() : this, g ? [a] : arguments)
                })
            }), a = null
        }).promise()
    }),
    done: (function() {
        if (h) {
            var d = h.length;
            ! function f(b) {
                m.each(b, function(b, c) {
                    var d = m.type(c);
                    "function" === d ? a.unique && k.has(c) || h.push(c) : c && c.length && "string" !== d && f(c)
                })
            }(arguments), b ? e = h.length : c && (g = d, j(c))
        }
        return this
    }),
    fail: (function() {
        if (h) {
            var d = h.length;
            ! function f(b) {
                m.each(b, function(b, c) {
                    var d = m.type(c);
                    "function" === d ? a.unique && k.has(c) || h.push(c) : c && c.length && "string" !== d && f(c)
                })
            }(arguments), b ? e = h.length : c && (g = d, j(c))
        }
        return this
    }),
    progress: (function() {
        if (h) {
            var d = h.length;
            ! function f(b) {
                m.each(b, function(b, c) {
                    var d = m.type(c);
                    "function" === d ? a.unique && k.has(c) || h.push(c) : c && c.length && "string" !== d && f(c)
                })
            }(arguments), b ? e = h.length : c && (g = d, j(c))
        }
        return this
    }),
    complete: (function() {
        if (h) {
            var d = h.length;
            ! function f(b) {
                m.each(b, function(b, c) {
                    var d = m.type(c);
                    "function" === d ? a.unique && k.has(c) || h.push(c) : c && c.length && "string" !== d && f(c)
                })
            }(arguments), b ? e = h.length : c && (g = d, j(c))
        }
        return this
    }),
    success: (function() {
        if (h) {
            var d = h.length;
            ! function f(b) {
                m.each(b, function(b, c) {
                    var d = m.type(c);
                    "function" === d ? a.unique && k.has(c) || h.push(c) : c && c.length && "string" !== d && f(c)
                })
            }(arguments), b ? e = h.length : c && (g = d, j(c))
        }
        return this
    }),
    error: (function() {
        if (h) {
            var d = h.length;
            ! function f(b) {
                m.each(b, function(b, c) {
                    var d = m.type(c);
                    "function" === d ? a.unique && k.has(c) || h.push(c) : c && c.length && "string" !== d && f(c)
                })
            }(arguments), b ? e = h.length : c && (g = d, j(c))
        }
        return this
    }),
    responseText: "",
    status: 0,
    statusText: "error"
})
```

**Comment by karlcow** [comment]
Trying to dig to understand what is happening.

I modified a bit of the code like this:

```js
      this._loadingIndicator.addClass('is-active');
      console.log(JSON.stringify(this.issues));
      console.log(this.issues.toSource());
      this.issues.fetch(headers)
        .success(_.bind(function() {
          console.log("inside success");
          this._loadingIndicator.removeClass('is-active');
          this.render(this.issues);
          issuesPagination.initPaginationLinks(this.issues);
          }, this))
        .error(_.bind(function(e) {
          console.log("inside error");
          var message;
```

and without breakpoint, it gives me.


```
14:37:02.621 [] issue-list.js:354:7
14:37:02.622 ({length:0, models:[], _byId:{}, params:{page:1, per_page:50, state:"open", stage:"all", sort:"created", direction:"desc"}, path:"/api/issues", url:"https://api.github.com/search/issues?page=1&per_page=50&stage=all&sort=created&q=vladvlad+state%3Aopen+repo%3Awebcompat%2Fwebcompat-tests&order=desc"}) issue-list.js:355:7
14:37:03.066 inside error issue-list.js:364:11
```

Also from [github doc](https://developer.github.com/v3/search/#timeouts-and-incomplete-results)
> To keep the Search API fast for everyone, we limit how long any individual query can run. For queries that exceed the time limit, the API returns the matches that were already found prior to the timeout, and the response has the incomplete_results property set to true.

**Comment by karlcow** [comment]
`this.issues.fetch(headers)` is basically 
`this.issues.fetch({"headers":{"Accept":"application/json"}})`

The only difference I see about issues before and after the error is

Before 
```
({length:0, models:[], _byId:{}, params:{page:1, per_page:50, state:"open", stage:"all", sort:"created", direction:"desc"}, path:"/api/issues", url:"https://api.github.com/search/issues?page=1&per_page=50&stage=all&sort=created&q=love+state%3Aopen+repo%3Awebcompat%2Fwebcompat-tests&order=desc"})
```

after

```
({length:0, models:[], _byId:{}, params:{page:"1", per_page:"50", state:"open", stage:"all", sort:"created", direction:"desc", q:"love"}, path:"/api/issues", url:"https://api.github.com/search/issues?page=1&per_page=50&stage=all&sort=created&q=love+state%3Aopen+repo%3Awebcompat%2Fwebcompat-tests&order=desc"})
```

aka `page:"1", per_page:"50"` got double quotes.

**Comment by karlcow** [comment]
It doesn't change anything but why

`.success(_.bind(function()`
`.error(_.bind(function(e)`

**Comment by miketaylr** [comment]
> It doesn't change anything but why

Can you clarify? Why are we not passing in `e` in the first? Or why we're using `_.bind()`?

**Comment by miketaylr** [comment]
> "{"readyState":0,"responseText":"","status":0,"statusText":"error"}"

OK. So seraching for similar things I see a few answers that refer to SOP: http://stackoverflow.com/questions/19395354/jquery-ajax-readystate-0-responsetext-status-0-statustext-error

That's... weird. Like I said, this has never failed locally for me, but seems to fail 100% of the time for you @karlcow? And fails some low % of the time for Travis.

Could it be something crazy like a GitHub server that's responding to Japan and not sending CORS headers? :grey_question:

**Comment by karlcow** [comment]
DOH! 👹😳
So my consistent failure was that I was testing in my browser with ublock, which was blocking github for localhost requests. /me is hiding under a THICK carpet.

Testing in a normal clean profile of Firefox. Everything is working.

BUT that doesn't solve our travis issue. :)

**Comment by miketaylr** [comment]
:dancer: 
(well, for one thing it caused us to examine where things *might* be going wrong. So it was a worthwhile exercise. :+1:)

**Comment by miketaylr** [comment]
I think we should remove this test and then add a new one. Right now this just ends up wasting time and Travis resources (having to re-trigger it until it succeeds).
